// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const SET_IMMERSE_UI_KEY = "SET_IMMERSE_UI_KEY"
export const SET_IMMERSE_UI_KEYS = "SET_IMMERSE_UI_KEYS"

export const ENABLE_ALL_IMMERSE_UI_KEYS = "ENABLE_ALL_IMMERSE_UI_KEYS"
export const DISABLE_ALL_IMMERSE_UI_KEYS = "DISABLE_ALL_IMMERSE_UI_KEYS"

export const IMMERSE_UI_NAVBAR = "IMMERSE_UI_NAVBAR"
export const IMMERSE_UI_HEADERBAR = "IMMERSE_UI_HEADERBAR"
export const IMMERSE_UI_SIDE_PANELS = "IMMERSE_UI_SIDE_PANELS"
export const IMMERSE_UI_FILTERS = "IMMERSE_UI_FILTERS"
export const IMMERSE_UI_PARAMETERS = "IMMERSE_UI_PARAMETERS"
export const IMMERSE_UI_CONFIG_UI = "IMMERSE_UI_CONFIG_UI"
export const IMMERSE_UI_CROSSLINK = "IMMERSE_UI_CROSSLINK"
export const IMMERSE_UI_FILTER_SETS = "IMMERSE_UI_FILTER_SETS"
export const IMMERSE_UI_ANNOTATION = "IMMERSE_UI_ANNOTATION"
export const IMMERSE_UI_SAVE = "IMMERSE_UI_SAVE"
export const IMMERSE_UI_REFRESH = "IMMERSE_UI_REFRESH"
export const IMMERSE_UI_ADD_CHART = "IMMERSE_UI_ADD_CHART"
export const IMMERSE_UI_ADD_TAB = "IMMERSE_UI_ADD_TAB"
export const IMMERSE_UI_USER_DROPDOWN = "IMMERSE_UI_USER_DROPDOWN"
export const IMMERSE_UI_HELP_DROPDOWN = "IMMERSE_UI_HELP_DROPDOWN"
export const IMMERSE_UI_SQL_EDITOR = "IMMERSE_UI_SQL_EDITOR"
export const IMMERSE_UI_SQL_NOTEBOOK = "IMMERSE_UI_SQL_NOTEBOOK"
export const IMMERSE_UI_JUPYTER_LABS = "IMMERSE_UI_JUPYTER_LABS"
export const IMMERSE_UI_DATA_MANAGER = "IMMERSE_UI_DATA_MANAGER"
export const IMMERSE_UI_DASHBOARDS = "IMMERSE_UI_DASHBOARDS"
export const IMMERSE_UI_TABS = "IMMERSE_UI_TABS"
export const IMMERSE_UI_GLOBAL_SIDE_NAV = "IMMERSE_UI_GLOBAL_SIDE_NAV"
export const IMMERSE_UI_GLOBAL_SIDE_NAV_TOGGLE =
  "IMMERSE_UI_GLOBAL_SIDE_NAV_TOGGLE"
export const IMMERSE_UI_ENTER_CHART_EDITOR = "IMMERSE_UI_ENTER_CHART_EDITOR"
export const IMMERSE_UI_DUPLICATE_CHART = "IMMERSE_UI_DUPLICATE_CHART"
export const IMMERSE_UI_DOWNLOAD_CSV = "IMMERSE_UI_DOWNLOAD_CSV"
export const IMMERSE_UI_REMOVE_CHART = "IMMERSE_UI_REMOVE_CHART"
export const IMMERSE_UI_CHART_KEBAB = "IMMERSE_UI_CHART_KEBAB"
export const IMMERSE_UI_CHART_RESIZE = "IMMERSE_UI_CHART_RESIZE"
export const IMMERSE_UI_CHART_MOVE = "IMMERSE_UI_CHART_MOVE"

export const defaultImmerseUIKeys = {
  [IMMERSE_UI_NAVBAR]: true, // works
  [IMMERSE_UI_HEADERBAR]: true, // works
  [IMMERSE_UI_SIDE_PANELS]: true, // works
  [IMMERSE_UI_FILTERS]: true, // works
  [IMMERSE_UI_PARAMETERS]: true, // works
  [IMMERSE_UI_CONFIG_UI]: true, // works
  [IMMERSE_UI_CROSSLINK]: true, // works
  [IMMERSE_UI_FILTER_SETS]: true, // works
  [IMMERSE_UI_ANNOTATION]: true, // works
  [IMMERSE_UI_SAVE]: true, // works
  [IMMERSE_UI_REFRESH]: true, // works
  [IMMERSE_UI_ADD_CHART]: true, // works
  [IMMERSE_UI_ADD_TAB]: true, // works
  [IMMERSE_UI_USER_DROPDOWN]: true, // works
  [IMMERSE_UI_HELP_DROPDOWN]: true, // works
  [IMMERSE_UI_SQL_EDITOR]: true, // works
  [IMMERSE_UI_SQL_NOTEBOOK]: true,
  [IMMERSE_UI_JUPYTER_LABS]: true, // works
  [IMMERSE_UI_DATA_MANAGER]: true, // works
  [IMMERSE_UI_DASHBOARDS]: true, // works
  [IMMERSE_UI_TABS]: true, // works
  [IMMERSE_UI_GLOBAL_SIDE_NAV]: true, // works
  [IMMERSE_UI_GLOBAL_SIDE_NAV_TOGGLE]: true, // works
  [IMMERSE_UI_ENTER_CHART_EDITOR]: true, // works
  [IMMERSE_UI_DUPLICATE_CHART]: true, // works
  [IMMERSE_UI_DOWNLOAD_CSV]: true, // works
  [IMMERSE_UI_REMOVE_CHART]: true, // works
  [IMMERSE_UI_CHART_KEBAB]: true, // works
  [IMMERSE_UI_CHART_RESIZE]: true,
  [IMMERSE_UI_CHART_MOVE]: true
}
