// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const REMOVE_ALL_PARAMETER_DEFINITIONS =
  "REMOVE_ALL_PARAMETER_DEFINITIONS"
export const ADD_PARAMETER_DEFINITION = "ADD_PARAMETER_DEFINITION"
export const UPDATE_PARAMETER_DEFINITION = "UPDATE_PARAMETER_DEFINITION"
export const REMOVE_PARAMETER_DEFINITION = "REMOVE_PARAMETER_DEFINITION"
export const RESET_PARAMETER_DEFS_FROM_SNAPSHOT =
  "RESET_PARAMETER_DEFS_FROM_SNAPSHOT"

export const REMOVE_ALL_PARAMETER_SETS = "REMOVE_ALL_PARAMETER_SETS"
export const RESET_PARAMETER_SETS_FROM_SNAPSHOT =
  "RESET_PARAMETER_SETS_FROM_SNAPSHOT"
export const ADD_PARAMETER_SET = "ADD_PARAMETER_SET"
export const SET_HIDE_HIDDEN_PARAMETER_SET = "SET_HIDE_HIDDEN_PARAMETER_SET"
export const REMOVE_PARAMETER_SETS = "REMOVE_PARAMETER_SETS"
export const RENAME_PARAMETER_SET = "RENAME_PARAMETER_SET"
export const DUPLICATE_PARAMETER_SET = "DUPLICATE_PARAMETER_SET"

export const REMOVE_ALL_PARAMETER_VALUES = "REMOVE_ALL_PARAMETER_VALUES"
export const RESET_PARAMETER_VALUES_FROM_SNAPSHOT =
  "RESET_PARAMETER_VALUES_FROM_SNAPSHOT"
export const SET_PARAMETER_VALUE = "SET_PARAMETER_VALUE"
export const REMOVE_PARAMETER_VALUE = "REMOVE_PARAMETER_VALUE"
export const SET_PARAMETER_DEFAULT = "SET_PARAMETER_DEFAULT"
export const REMOVE_PARAMETER_DEFAULT = "REMOVE_PARAMETER_DEFAULT"
export const SET_PARAMETER_HIDE = "SET_PARAMETER_HIDE"

export const NOTE_PARAMETER_USAGE = "NOTE_PARAMETER_USAGE"
export const NOTE_CROSSFILTER_PARAMETER_USAGE =
  "NOTE_CROSSFILTER_PARAMETER_USAGE"
export const CLEAR_PARAMETER_USAGE = "CLEAR_PARAMETER_USAGE"
export const REMOVE_CHART_FROM_PARAMETER_USAGE =
  "REMOVE_CHART_FROM_PARAMETER_USAGE"
export const RESET_PARAMETERS_USAGE_FROM_SNAPSHOT =
  "RESET_PARAMETERS_USAGE_FROM_SNAPSHOT"

export const CLEAR_PARAMETER_VALUES = "CLEAR_PARAMETER_VALUES"
export const RESET_PARAMETER_FROM_SNAPSHOT = "RESET_PARAMETER_FROM_SNAPSHOT"

export const ADD_PARAMETER_DASHBOARD_WIDGET = "ADD_PARAMETER_DASHBOARD_WIDGET"
export const REMOVE_PARAMETER_DASHBOARD_WIDGET =
  "REMOVE_PARAMETER_DASHBOARD_WIDGET"

export const ADD_PARAMETER_TO_PANEL = "ADD_PARAMETER_TO_PANEL"
export const REMOVE_PARAMETER_FROM_PANEL = "REMOVE_PARAMETER_FROM_PANEL"

export const NUMBER_STEP_PRECISIONS = {
  AUTO: "auto",
  0: "1",
  1: "0.1",
  2: "0.01",
  3: "0.001",
  4: "0.0001",
  5: "0.00001"
}
