// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// SQL Notebook
export const SQL_NOTEBOOK_EXECUTE_REQUEST = "SQL_NOTEBOOK_EXECUTE_REQUEST"
export const SQL_NOTEBOOK_EXECUTE_SUCCESS = "SQL_NOTEBOOK_EXECUTE_SUCCESS"
export const SQL_NOTEBOOK_EXECUTE_ERROR = "SQL_NOTEBOOK_EXECUTE_ERROR"
export const SQL_NOTEBOOK_ADD_CELL = "SQL_NOTEBOOK_ADD_CELL"
export const SQL_NOTEBOOK_SET_EDITING = "SQL_NOTEBOOK_SET_EDITING"
export const SQL_NOTEBOOK_SET_INPUT = "SQL_NOTEBOOK_SET_INPUT"
export const SQL_NOTEBOOK_SET_SOURCES = "SQL_NOTEBOOK_SET_SOURCES"
export const SQL_NOTEBOOK_SET_CELL_TYPE = "SQL_NOTEBOOK_SET_CELL_TYPE"
export const SQL_NOTEBOOK_SET_LOADING = "SQL_NOTEBOOK_SET_LOADING"
export const SQL_NOTEBOOK_IQ_REQUEST = "SQL_NOTEBOOK_IQ_REQUEST"
export const SQL_NOTEBOOK_IQ_SUCCESS = "SQL_NOTEBOOK_IQ_SUCCESS"
export const SQL_NOTEBOOK_IQ_ERROR = "SQL_NOTEBOOK_IQ_ERROR"
export const SQL_NOTEBOOK_IQ_GENERATED_SQL_ERROR =
  "SQL_NOTEBOOK_IQ_GENERATED_SQL_ERROR"
export const SQL_NOTEBOOK_ADD_INPUT_ANALYSIS_CELL =
  "SQL_NOTEBOOK_ADD_INPUT_ANALYSIS_CELL"
export const SQL_NOTEBOOK_SET_DEFAULT_SOURCES =
  "SQL_NOTEBOOK_SET_DEFAULT_SOURCES"
export const SQL_NOTEBOOK_SET_ACTIVE_TAB = "SQL_NOTEBOOK_SET_ACTIVE_TAB"
export const SQL_NOTEBOOK_SET_HIDE_ANALYSIS = "SQL_NOTEBOOK_SET_HIDE_ANALYSIS"
export const SQL_NOTEBOOK_SET_FASTFORWARD = "SQL_NOTEBOOK_SET_FASTFORWARD"
export const SQL_NOTEBOOK_SET_FASTFORWARD_DEFAULT =
  "SQL_NOTEBOOK_SET_FASTFORWARD_DEFAULT"
export const SQL_NOTEBOOK_SET_IQ_ENABLED = "SQL_NOTEBOOK_SET_IQ_ENABLED"
export const SQL_NOTEBOOK_ADD_GUIDANCE_SNIPPETS =
  "SQL_NOTEBOOK_ADD_GUIDANCE_SNIPPETS"
export const SQL_NOTEBOOK_GET_GUIDANCE_SNIPPETS_REQUEST =
  "SQL_NOTEBOOK_GET_GUIDANCE_SNIPPETS_REQUEST"
export const SQL_NOTEBOOK_GET_GUIDANCE_SNIPPETS_SUCCESS =
  "SQL_NOTEBOOK_GET_GUIDANCE_SNIPPETS_SUCCESS"
export const SQL_NOTEBOOK_GET_GUIDANCE_SNIPPETS_ERROR =
  "SQL_NOTEBOOK_GET_GUIDANCE_SNIPPETS_ERROR"
export const SQL_NOTEBOOK_DELETE_GUIDANCE_SNIPPETS =
  "SQL_NOTEBOOK_DELETE_GUIDANCE_SNIPPETS"
export const SQL_NOTEBOOK_UPDATE_GUIDANCE_SNIPPET =
  "SQL_NOTEBOOK_UPDATE_GUIDANCE_SNIPPET"
export const SQL_NOTEBOOK_UNDO_DELETED_GUIDANCE_SNIPPETS =
  "SQL_NOTEBOOK_UNDO_DELETED_GUIDANCE_SNIPPETS"
export const SQL_NOTEBOOK_CLEAR_DELETED_GUIDANCE_SNIPPETS =
  "SQL_NOTEBOOK_CLEAR_DELETED_GUIDANCE_SNIPPETS"
export const SQL_NOTEBOOK_GUIDANCE_SET_LOADING =
  "SQL_NOTEBOOK_GUIDANCE_SET_LOADING"
export const SQL_NOTEBOOK_OPEN_GUIDANCE_MODAL =
  "SQL_NOTEBOOK_OPEN_GUIDANCE_MODAL"
export const SQL_NOTEBOOK_CLOSE_GUIDANCE_MODAL =
  "SQL_NOTEBOOK_CLOSE_GUIDANCE_MODAL"
