// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import * as ChartUpdateActionTypes from "constants/chart-update-action-types"

export const BATCH_ACTIONS = "BATCH_ACTIONS"

// SessionValid
export const SET_SESSION_VALID = "SET_SESSION_VALID"
export const SET_SESSION_INVALID = "SET_SESSION_INVALID"
export const SET_IDLE_SESSION_DURATION = "SET_IDLE_SESSION_DURATION"
export const SET_MAX_SESSION_DURATION = "SET_MAX_SESSION_DURATION"

// Connection

export const INIT_HEAVYDB_SESSION = "INIT_HEAVYDB_SESSION"
export const CONNECTION_ERROR = "CONNECTION_ERROR"
export const CONNECTION_REQUEST = "CONNECTION_REQUEST"
export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS"
export const UPDATE_SESSION_INFO = "UPDATE_SESSION_INFO"
export const UPDATE_SESSION_ID = "UPDATE_SESSION_ID"
export const SET_CONNECTION_INFO = "SET_CONNECTION_INFO"
export const SET_USER_DATA = "SET_USER_DATA"
export const DROP_CONNECTION = "DROP_CONNECTION"
export const LOAD_GEOJSON_CONFIG = "LOAD_GEOJSON_CONFIG"
export const RETURN_ON_LOGIN = "RETURN_ON_LOGIN"
export const SET_DATABASE_NAME = "SET_DATABASE_NAME"
export const SET_USER_PRIVILEGES = "SET_USER_PRIVILEGES"
export const SET_USER_ROLES = "SET_USER_ROLES"
export const CONNECTION_TIMEOUT_ERROR = "CONNECTION_TIMEOUT_ERROR"

// Nav Bar

export const TOGGLE_HELP_MENU = "TOGGLE_HELP_MENU"
export const TOGGLE_USER_MENU = "TOGGLE_USER_MENU"
export const TOGGLE_DOCS_MENU = "TOGGLE_DOCS_MENU"
export const SHOW_UNSAVED_CHANGES_DIALOG = "SHOW_UNSAVED_CHANGES_DIALOG"
export const ROUTE_TO_HOME_OVERRIDE = "ROUTE_TO_HOME_OVERRIDE"
export const ROUTE_TO_COMMUNITY_FORUM = "ROUTE_TO_COMMUNITY_FORUM"
export const ROUTE_TO_DOCUMENTATION = "ROUTE_TO_DOCUMENTATION"
export const ROUTE_TO_TUTORIALS = "ROUTE_TO_TUTORIALS"
export const HANDLE_LOGOUT_CLICK = "HANDLE_LOGOUT_CLICK"
export const HANDLE_ERROR_LOGOUT = "HANDLE_ERROR_LOGOUT"
export const HANDLE_HOME_CLICK = "HANDLE_HOME_CLICK"
export const HANDLE_ABOUT_CLICK = "HANDLE_ABOUT_CLICK"

// Charts

export const ADD_CHART = "ADD_CHART"
export const DUPLICATE_CHART = "DUPLICATE_CHART"
export const CREATE_NEW_DASHBOARD = "CREATE_NEW_DASHBOARD"
export const COPY_DASHBOARD = "COPY_DASHBOARD"
export const CONFIRM_COPY_DASHBOARD_ERROR = "CONFIRM_COPY_DASHBOARD_ERROR"
export const COPY_DASHBOARD_ERROR_SET_MESSAGE =
  "COPY_DASHBOARD_ERROR_SET_MESSAGE"
export const CLEAR_DASHBOARD = "CLEAR_DASHBOARD"
export const CONFIRM_DELETE_DASHBOARD_ERROR = "CONFIRM_DELETE_DASHBOARD_ERROR"
export const DELETE_DASHBOARD_ERROR = "DELETE_DASHBOARD_ERROR"
export const DELETE_DASHBOARD_REQUEST = "DELETE_DASHBOARD_REQUEST"
export const DELETE_DASHBOARD_SUCCESS = "DELETE_DASHBOARD_SUCCESS"
export const DELETE_DASHBOARD_DONE = "DELETE_DASHBOARD_DONE"
export const LOAD_DASHBOARD = "LOAD_DASHBOARD"
export const LOAD_DASHBOARD_REQUEST = "LOAD_DASHBOARD_REQUEST"
export const LOAD_DASHBOARD_SUCCESS = "LOAD_DASHBOARD_SUCCESS"
export const LOAD_DASHBOARD_ERROR = "LOAD_DASHBOARD_ERROR"
export const LOAD_DASHBOARD_DATA_ACCESS_ERROR =
  "LOAD_DASHBOARD_DATA_ACCESS_ERROR"
export const CONFIRM_LOAD_DASHBOARD_DATA_ACCESS_ERROR =
  "CONFIRM_LOAD_DASHBOARD_DATA_ACCESS_ERROR"
export const SAVE_DASHBOARD_SUCCESS = "SAVE_DASHBOARD_SUCCESS"
export const SAVE_DASHBOARD_REQUEST = "SAVE_DASHBOARD_REQUEST"
export const SAVE_DASHBOARD_ERROR = "SAVE_DASHBOARD_ERROR"
export const CONFIRM_SAVE_DASHBOARD_ERROR = "CONFIRM_SAVE_DASHBOARD_ERROR"
export const SET_LOADLINK_ID = "SET_LOADLINK_ID"

export const UPDATE_LAYOUT = "UPDATE_LAYOUT"
export const UPDATE_LAYOUT_FOR_CHART = "UPDATE_LAYOUT_FOR_CHART"
export const UPDATE_DASHBOARD_NAME = "UPDATE_DASHBOARD_NAME"
export const UPDATE_DASHBOARD_NAME_FORMATTED = "UPDATE_DASHBOARD_NAME_FORMATTED"
export const UPDATE_DASHBOARD_SAVE_STATE = "UPDATE_DASHBOARD_SAVE_STATE"
export const SET_SELECTOR_ERROR = "SET_SELECTOR_ERROR"
export const SET_CHART_HAS_ERROR = "SET_CHART_HAS_ERROR"
export const CLEAR_CHART_HAS_ERROR = "CLEAR_CHART_HAS_ERROR"
export const SET_CHART_DATA_ERROR = "SET_CHART_DATA_ERROR"
export const SET_CHART_DC_FLAG = "SET_CHART_DC_FLAG"
export const DISCARD_INACTIVE_SELECTORS = "DISCARD_INACTIVE_SELECTORS"
export const ADD_CUSTOM_MEASURE = ChartUpdateActionTypes.ADD_CUSTOM_MEASURE
export const ADD_MEASURE = ChartUpdateActionTypes.ADD_MEASURE
export const ADD_DIMENSION = ChartUpdateActionTypes.ADD_DIMENSION
export const CREATE_CHART = ChartUpdateActionTypes.CREATE_CHART

export const CLEAR_CHART_FILTERS = ChartUpdateActionTypes.CLEAR_CHART_FILTERS
export const SET_CHART_FILTERS = ChartUpdateActionTypes.SET_CHART_FILTERS
export const CLEAR_CHART_FILTERS_FOR_ALL_CHARTS =
  ChartUpdateActionTypes.CLEAR_CHART_FILTERS_FOR_ALL_CHARTS
export const REMOVE_SELECTOR = ChartUpdateActionTypes.REMOVE_SELECTOR
export const CLEAR_SELECTOR = ChartUpdateActionTypes.CLEAR_SELECTOR
export const SWAP_SELECTORS = ChartUpdateActionTypes.SWAP_SELECTORS
export const UPDATE_SELECTOR = ChartUpdateActionTypes.UPDATE_SELECTOR
export const UPDATE_CHART_TYPE = ChartUpdateActionTypes.UPDATE_CHART_TYPE
export const UPDATE_CHART = ChartUpdateActionTypes.UPDATE_CHART
export const SET_CHART_STATE = ChartUpdateActionTypes.SET_CHART_STATE
export const UPDATE_CHART_COLORS = "UPDATE_CHART_COLORS"
export const UPDATE_BIN_PARAMS = ChartUpdateActionTypes.UPDATE_BIN_PARAMS
export const SET_ELASTICX = "SET_ELASTICX"
export const SET_ELASTICY = "SET_ELASTICY"
export const UPDATE_MEASURE_DOMAINS = "UPDATE_MEASURE_DOMAINS"
export const TOGGLE_OTHER = "TOGGLE_OTHER"
export const TOGGLE_OTHER_MULTI_SOURCE = "TOGGLE_OTHER_MULTI_SOURCE"
export const TOGGLE_OTHER_RASTER = "TOGGLE_OTHER_RASTER"
export const SET_CUSTOM_DEFAULT_OTHER_COLOR = "SET_CUSTOM_DEFAULT_OTHER_COLOR"
export const SET_CUSTOM_COLOR = "SET_CUSTOM_COLOR"
export const REMOVE_CUSTOM_COLOR = "REMOVE_CUSTOM_COLOR"
export const REMOVE_CUSTOM_COLOR_MULTI_SOURCE =
  "REMOVE_CUSTOM_COLOR_MULTI_SOURCE"
export const UPDATE_HIDE_OTHER = "UPDATE_HIDE_OTHER"
export const ADD_CUSTOM_COLOR = "ADD_CUSTOM_COLOR"
export const ADD_CUSTOM_COLOR_MULTI_SOURCE = "ADD_CUSTOM_COLOR_MULTI_SOURCE"
export const ADD_CUSTOM_COLOR_DOMAIN = "ADD_CUSTOM_COLOR_DOMAIN"
export const SET_BASEMAP = "SET_BASEMAP"
export const REMOVE_COUNT_CHART = "REMOVE_COUNT_CHART"
export const TOGGLE_PERCENTAGE_VIEW = "TOGGLE_PERCENTAGE_VIEW"
export const TOGGLE_CHART_LEGEND = "TOGGLE_CHART_LEGEND"
export const CLEAR_SAVED_COLORS_BY_DIMENSION = "CLEAR_SAVED_COLORS_BY_DIMENSION"
export const INITIALIZE_COLOR_RAMPS = "INITIALIZE_COLOR_RAMPS"
export const UPDATE_COLOR_RAMPS = "UPDATE_COLOR_RAMPS"
export const REMOVE_CUSTOM_DOMAIN_RANGE = "REMOVE_CUSTOM_DOMAIN_RANGE"
export const UPDATE_D3_CHART_COLOR_PALETTE = "UPDATE_D3_CHART_COLOR_PALETTE"
export const CLEAR_D3_CHART_COLOR = "CLEAR_D3_CHART_COLOR"

export const HIGHLIGHT_CHARTS = "HIGHLIGHT_CHARTS"
export const DEHIGHLIGHT_CHARTS = "DEHIGHLIGHT_CHARTS"

export const TOGGLE_QUICK_FILTERS_EXPANDED = "TOGGLE_QUICK_FILTERS_EXPANDED"

export const SET_INIT_X_DOMAIN = "SET_INIT_X_DOMAIN"
export const SET_INIT_Y_DOMAIN = "SET_INIT_Y_DOMAIN"

// Dashboard

export const CLEAR_CHARTS = "CLEAR_CHARTS"
export const DELETE_CHART = "DELETE_CHART"
export const INITIALIZE_DASHBOARD = "INITIALIZE_DASHBOARD"
export const INITIALIZE_JOIN_TABLE = "INITIALIZE_JOIN_TABLE"
export const CLEAR_JOIN_TABLE = "CLEAR_JOIN_TABLE"
export const GET_VIEW_AND_LOAD = "GET_VIEW_AND_LOAD"
export const LOAD_DASHBOARD_TAB = "LOAD_DASHBOARD_TAB"
export const DASHBOARD_ADD_DATA_SOURCE = "DASHBOARD_ADD_DATA_SOURCE"
export const DASHBOARD_DELETE_DATA_SOURCE = "DASHBOARD_DELETE_DATA_SOURCE"
export const SAVE_CURRENT_CHART = "SAVE_CURRENT_CHART"
export const SAVE_CHARTS_SNAPSHOT = "SAVE_CHARTS_SNAPSHOT"
export const SET_CHART_EDITOR_TO_INITIAL_STATE =
  "SET_CHART_EDITOR_TO_INITIAL_STATE"
export const APPLY_CHART_EDITS = "APPLY_CHART_EDITS"
export const CANCEL_CHART_EDITS = "CANCEL_CHART_EDITS"
export const INIT_CHART_EDITOR_TABLE_PREVIEW = "INIT_CHART_EDITOR_TABLE_PREVIEW"
export const SET_CHART_EDITOR_TABLE_PREVIEW = "SET_CHART_EDITOR_TABLE_PREVIEW"

export const ENTER_MULTI_SOURCE_MODE = "ENTER_MULTI_SOURCE_MODE"
export const ADD_MULTI_SOURCE = "ADD_MULTI_SOURCE"
export const DELETE_MULTI_SOURCE = "DELETE_MULTI_SOURCE"
export const CLEAR_MULTI_SOURCE = "CLEAR_MULTI_SOURCE"
export const SELECT_MULTI_SOURCE_PANEL = "SELECT_MULTI_SOURCE_PANEL"
export const LEAVE_MULTI_SOURCE_MODE = "LEAVE_MULTI_SOURCE_MODE"

export const ADD_TABLES_SUCCESS = "ADD_TABLES_SUCCESS"
export const ADD_TABLES_WITH_META_SUCCESS = "ADD_TABLES_WITH_META_SUCCESS"
export const START_TABLES_REQUEST = "START_TABLES_REQUEST"
export const TABLES_TRANSACTION_ERROR = "TABLES_TRANSACTION_ERROR"
export const CONFIRM_TABLES_TRANSACTION_ERROR =
  "CONFIRM_TABLES_TRANSACTION_ERROR"

export const ADD_TABLES_REF_ERROR = "ADD_TABLES_REF_ERROR"
export const ADD_TABLES_REF_REQUEST = "ADD_TABLES_REF_REQUEST"
export const ADD_TABLES_REF_SUCCESS = "ADD_TABLES_REF_SUCCESS"

export const DROP_TABLE_SUCCESS = "DROP_TABLE_SUCCESS"
export const TRUNC_TABLE_SUCCESS = "TRUNC_TABLE_SUCCESS"

export const CONFIRM_GET_DASHBOARDS_ERROR = "CONFIRM_GET_DASHBOARDS_ERROR"
export const GET_DASHBOARDS_ERROR = "GET_DASHBOARDS_ERROR"
export const GET_DASHBOARDS_REQUEST = "GET_DASHBOARDS_REQUEST"
export const GET_DASHBOARDS_SUCCESS = "GET_DASHBOARDS_SUCCESS"

export const EXPORT_DASHBOARD_ERROR = "EXPORT_DASHBOARD_ERROR"
export const IMPORT_DASHBOARD_ERROR = "IMPORT_DASHBOARD_ERROR"
export const ACCEPT_IMPORT_ERROR = "ACCEPT_IMPORT_ERROR"

export const TOGGLE_DASHBOARD = "TOGGLE_DASHBOARD"
export const SELECT_ALL_DASHBOARDS_IN_LIST = "SELECT_ALL_DASHBOARDS_IN_LIST"
export const DESELECT_ALL_DASHBOARDS_IN_LIST = "DESELECT_ALL_DASHBOARDS_IN_LIST"
export const CLEAR_ALL_DASHBOARD_SELECTIONS = "CLEAR_ALL_DASHBOARD_SELECTIONS"

export const SET_DASHBOARD_CONFIG_PANEL_WIDTH =
  "SET_DASHBOARD_CONFIG_PANEL_WIDTH"

// CrossLink
export const SAVE_CROSSLINK = "SAVE_CROSSLINK"
export const TOGGLE_CROSSLINK = "TOGGLE_CROSSLINK"
export const DELETE_CROSSLINK = "DELETE_CROSSLINK"

// Table picker actions
export const SET_TABLE_PICKER_SEARCH_VAL = "SET_TABLE_PICKER_SEARCH_VAL"
export const GET_DATA_SOURCE_PREVIEW_ERROR = "GET_DATA_SOURCE_PREVIEW_ERROR"
export const GET_DATA_SOURCE_PREVIEW_REQUEST = "GET_DATA_SOURCE_PREVIEW_REQUEST"
export const GET_DATA_SOURCE_PREVIEW_SUCCESS = "GET_DATA_SOURCE_PREVIEW_SUCCESS"
export const SELECT_PREVIEW_TABLE = "SELECT_PREVIEW_TABLE"
export const RESET_PREVIEW_TABLE = "RESET_PREVIEW_TABLE"
export const SET_DATA_SOURCE_PRIVS = "SET_DATA_SOURCE_PRIVS"
export const SET_DATA_SOURCE_COMMENT = "SET_DATA_SOURCE_COMMENT"
export const SET_COLUMN_COMMENT = "SET_COLUMN_COMMENT"

export const SET_DATASOURCES = "SET_DATASOURCES"
export const DELETE_DATASOURCE = "DELETE_DATASOURCE"
export const SET_CURRENT_DATASOURCE = "SET_CURRENT_DATASOURCE"

export const LOAD_DASH = "LOAD_DASH"

export const ADD_DASHBOARD_TAB = "ADD_DASHBOARD_TAB"
export const DUPLICATE_DASHBOARD_TAB = "DUPLICATE_DASHBOARD_TAB"
export const REMOVE_DASHBOARD_TAB = "REMOVE_DASHBOARD_TAB"
export const RENAME_DASHBOARD_TAB = "RENAME_DASHBOARD_TAB"
export const SET_DASHBOARD_TAB = "SET_DASHBOARD_TAB"
export const SET_DASHBOARD_TAB_ORDER = "SET_DASHBOARD_TAB_ORDER"
export const COPY_COMMON_TAB_STATE = "COPY_COMMON_TAB_STATE"

export const SET_DASHBOARD_LOAD_PENDING = "SET_DASHBOARD_LOAD_PENDING"
export const SET_DASHBOARD_LOAD_SUCCESS = "SET_DASHBOARD_LOAD_SUCCESS"

export const SET_DASHBOARD_STYLES = "SET_DASHBOARD_STYLES"
export const RESET_DASHBOARD_STYLES = "RESET_DASHBOARD_STYLES"

export const UPDATE_CHART_BIN_EXTENT = "UPDATE_CHART_BIN_EXTENT"
export const SET_DIMENSION_EXTENTS_SET = "SET_DIMENSION_EXTENTS_SET"
export const REFRESH_BINNED_DATA = "REFRESH_BINNED_DATA"
export const SET_STREAMING_INTERVAL = "SET_STREAMING_INTERVAL"
export const TOGGLE_STREAMING = "TOGGLE_STREAMING"
export const REFRESH_DASHBOARD_COMPLETE = "REFRESH_DASHBOARD_COMPLETE"
export const REFRESH_DASHBOARD_REQUEST = "REFRESH_DASHBOARD_REQUEST"
export const REFRESH_DASHBOARD = "REFRESH_DASHBOARD"
export const SET_STREAMING_INTERVAL_REQUEST = "SET_STREAMING_INTERVAL_REQUEST"

export const SET_DASHBOARD_PRIVILEGES = "SET_DASHBOARD_PRIVILEGES"

// Dashboard Sharing
export const OPEN_DASHBOARD_SHARE_MODAL = "OPEN_DASHBOARD_SHARE_MODAL"
export const OPEN_DASHBOARD_BULK_SHARE_MODAL = "OPEN_DASHBOARD_BULK_SHARE_MODAL"
export const CLOSE_DASHBOARD_SHARE_MODAL = "CLOSE_DASHBOARD_SHARE_MODAL"
export const GET_ALL_USERS_AND_ROLES = "GET_ALL_USERS_AND_ROLES"
export const GET_DASHBOARD_GRANTEES = "GET_DASHBOARD_GRANTEES"
export const POPULATE_DASHBOARD_SHARED_USERS_LIST =
  "POPULATE_DASHBOARD_SHARED_USERS_LIST"
export const UPDATE_DASHBOARD_SHARED_USERS_LIST =
  "UPDATE_DASHBOARD_SHARED_USERS_LIST"
export const ADD_DASHBOARD_SHARED_USER = "ADD_DASHBOARD_SHARED_USER"
export const REMOVE_DASHBOARD_SHARED_USER = "REMOVE_DASHBOARD_SHARED_USER"
export const UPDATE_DASHBOARD_SHARE_AUTOSUGGEST_VALUE =
  "UPDATE_DASHBOARD_SHARE_AUTOSUGGEST_VALUE"
export const UPDATE_DASHBOARD_SHARE_SUGGESTIONS =
  "UPDATE_DASHBOARD_SHARE_SUGGESTIONS"

// UI

export const HIDE_CLEAR_FILTERS_DROPDOWN = "HIDE_CLEAR_FILTERS_DROPDOWN"
export const SHOW_CLEAR_FILTERS_DROPDOWN = "SHOW_CLEAR_FILTERS_DROPDOWN"
export const SHOW_MODAL = "SHOW_MODAL"
export const HIDE_MODAL = "HIDE_MODAL"
export const MODAL_LOADING = "MODAL_LOADING"
export const MODAL_DONE = "MODAL_DONE"
export const SELECTOR_PILL_HOVER = "SELECTOR_PILL_HOVER"
export const SELECTOR_PILL_NOT_HOVER = "SELECTOR_PILL_NOT_HOVER"
export const SET_SELECTOR_POSITION = "SET_SELECTOR_POSITION"

export const REMOVE_DASHBOARD_FILTER_REQUEST = "REMOVE_DASHBOARD_FILTER_REQUEST"
export const REMOVE_DASHBOARD_FILTER_SUCCESS = "REMOVE_DASHBOARD_FILTER_SUCCESS"
export const REMOVE_DASHBOARD_FILTER_ERROR = "REMOVE_DASHBOARD_FILTER_ERROR"
export const SHOW_DASHBOARD_IMPORT_MODAL = "SHOW_DASHBOARD_IMPORT_MODAL"
export const SHOW_DANGER_MODAL = "SHOW_DANGER_MODAL"
export const HIDE_DANGER_MODAL = "HIDE_DANGER_MODAL"
export const SHOW_INFO_MODAL = "SHOW_INFO_MODAL"
export const HIDE_INFO_MODAL = "HIDE_INFO_MODAL"
export const SHOW_WARNING_MODAL = "SHOW_WARNING_MODAL"
export const HIDE_WARNING_MODAL = "HIDE_WARNING_MODAL"
export const SHOW_BANNER = "SHOW_BANNER"
export const HIDE_BANNER = "HIDE_BANNER"
export const UPDATE_DISTINCT_COLUMN_VALUES = "UPDATE_DISTINCT_VALUES"
export const SET_FILTER_NEWLY_CREATED = "SET_FILTER_NEWLY_CREATED"
export const UNSET_FILTER_NEWLY_CREATED = "UNSET_FILTER_NEWLY_CREATED"
export const SET_CUSTOM_SQL_FILTER_VALIDATION_ERROR =
  "SET_CUSTOM_SQL_FILTER_VALIDATION_ERROR"
export const SET_FILTER_PANEL_VIEW_MODE = "SET_FILTER_PANEL_VIEW_MODE"

// DC

export const REDRAW_ALL_REQUEST = "REDRAW_ALL_REQUEST"
export const REDRAW_ALL_SUCCESS = "REDRAW_ALL_SUCCESS"
export const REDRAW_ALL_ERROR = "REDRAW_ALL_ERROR"
export const RENDER_ALL_REQUEST = "RENDER_ALL_REQUEST"
export const RENDER_ALL_SUCCESS = "RENDER_ALL_SUCCESS"
export const RENDER_ALL_ERROR = "RENDER_ALL_ERROR"
export const CHART_RENDER_REQUEST = "CHART_RENDER_REQUEST"
export const CHART_RENDER_SUCCESS = "CHART_RENDER_SUCCESS"
export const CHART_RENDER_ERROR = "CHART_RENDER_ERROR"
export const CHART_REDRAW_REQUEST = "CHART_REDRAW_REQUEST"
export const CHART_REDRAW_SUCCESS = "CHART_REDRAW_SUCCESS"
export const CHART_REDRAW_ERROR = "CHART_REDRAW_ERROR"
export const INITIAL_RENDER_BEGIN = "INITIAL_RENDER_BEGIN"
export const INITIAL_RENDER_DONE = "INITIAL_RENDER_DONE"
export const INITIAL_RENDER_ERROR = "INITIAL_RENDER_ERROR"
export const RESET_SPECIFIC_DC_STATE = "RESET_SPECIFIC_DC_STATE"
export const SET_DC_CHART_AXIS_DOMAIN = "SET_DC_CHART_AXIS_DOMAIN"

// Importer

export const CONFIRM_CREATE_NEW_TABLE_ERROR = "CONFIRM_CREATE_NEW_TABLE_ERROR"
export const CONFIRM_GET_IMPORT_PREVIEW_DATA_ERROR =
  "CONFIRM_GET_IMPORT_PREVIEW_DATA_ERROR"
export const CONFIRM_IMPORT_TABLE_ERROR = "CONFIRM_IMPORT_TABLE_ERROR"
export const CLEAR_COLUMN_NAME_LIST = "CLEAR_COLUMN_NAME_LIST"
export const CREATE_NEW_TABLE_ERROR = "CREATE_NEW_TABLE_ERROR"
export const CREATE_NEW_TABLE_REQUEST = "CREATE_NEW_TABLE_REQUEST"
export const CREATE_NEW_TABLE_SUCCESS = "CREATE_NEW_TABLE_SUCCESS"
export const GET_DATA_CATALOG_ERROR = "GET_DATA_CATALOG_ERROR"
export const GET_DATA_CATALOG_REQUEST = "GET_DATA_CATALOG_REQUEST"
export const GET_DATA_CATALOG_SUCCESS = "GET_DATA_CATALOG_SUCCESS"
export const GET_IMPORT_PREVIEW_DATA_ERROR = "GET_IMPORT_PREVIEW_DATA_ERROR"
export const GET_IMPORT_PREVIEW_DATA_REQUEST = "GET_IMPORT_PREVIEW_DATA_REQUEST"
export const GET_IMPORT_PREVIEW_DATA_SUCCESS = "GET_IMPORT_PREVIEW_DATA_SUCCESS"
export const LOAD_DATA_CATALOG_FILE_ERROR = "LOAD_DATA_CATALOG_FILE_ERROR"
export const LOAD_DATA_CATALOG_FILE_REQUEST = "LOAD_DATA_CATALOG_FILE_REQUEST"
export const LOAD_DATA_CATALOG_FILE_SUCCESS = "LOAD_DATA_CATALOG_FILE_SUCCESS"
export const UPDATE_IMPORT_START_TIME = "UPDATE_IMPORT_START_TIME"
export const UPDATE_IMPORT_END_TIME = "UPDATE_IMPORT_END_TIME"
export const CLEAR_IMPORT_STATUS = "CLEAR_IMPORT_STATUS"
export const GET_IMPORT_STATUS_SUCCESS = "GET_IMPORT_STATUS_SUCCESS"
export const ADD_ESTIMATED_END_TIME = "ADD_ESTIMATED_END_TIME"
export const IMPORT_TABLE_COMPLETE = "IMPORT_TABLE_COMPLETE"
export const IMPORT_TABLE_ERROR = "IMPORT_TABLE_ERROR"
export const IMPORT_TABLE_REQUEST = "IMPORT_TABLE_REQUEST"
export const IMPORT_TABLE_SUCCESS = "IMPORT_TABLE_SUCCESS"
export const REMOVE_IMPORT_FILES_ERROR = "REMOVE_IMPORT_FILES_ERROR"
export const REMOVE_IMPORT_FILES_REQUEST = "REMOVE_IMPORT_FILES_REQUEST"
export const REMOVE_IMPORT_FILES_SUCCESS = "REMOVE_IMPORT_FILES_SUCCESS"
export const RESET_IMPORTER = "RESET_IMPORTER"
export const UPDATE_COLUMN_NAME = "UPDATE_COLUMN_NAME"
export const UPDATE_IMPORTER_SETTING = "UPDATE_IMPORTER_SETTING"
export const UPDATE_TABLE_NAME = "UPDATE_TABLE_NAME"
export const UPDATE_TABLE_COMMENT = "UPDATE_TABLE_COMMENT"
export const UPDATE_COLUMN_TYPE = "UPDATE_COLUMN_TYPE"
export const UPDATE_COLUMN_COMMENT = "UPDATE_COLUMN_COMMENT"
export const SUBMIT_LOCAL_FILE_CONNECTOR = "SUBMIT_LOCAL_FILE_CONNECTOR"
export const SUBMIT_SERVER_FILE_CONNECTOR = "SUBMIT_SERVER_FILE_CONNECTOR"
export const SUBMIT_DATA_CATALOG_CONNECTOR = "SUBMIT_DATA_CATALOG_CONNECTOR"
export const SUBMIT_S3_CONNECTOR = "SUBMIT_S3_CONNECTOR"
export const SUBMIT_ODBC_CONNECTOR = "SUBMIT_ODBC_CONNECTOR"
export const TOGGLE_IMPORT_SETTINGS_MODAL = "TOGGLE_IMPORT_SETTINGS_MODAL"
export const SET_FSI_CONNECT_REFRESH_INFO = "SET_FSI_CONNECT_REFRESH_INFO"
export const SET_IMPORT_SETTINGS = "SET_IMPORT_SETTINGS"

// Global

export const RESET_APP_STATE = "RESET_APP_STATE"
export const SAVE_LAST_CHART_ACTION = "SAVE_LAST_CHART_ACTION"
export const SET_APP_ERROR = "SET_APP_ERROR"
export const RESET_APP_ERROR = "RESET_APP_ERROR"
export const SET_USER_AGENT = "SET_USER_AGENT"

// Filter Autosuggest

export const CLEAR_ALL_INPUT_FILTERS = "CLEAR_ALL_INPUT_FILTERS"
export const REMOVE_INPUT_FILTER = "REMOVE_INPUT_FILTER"

export const GET_FILTER_SIZE_REQUEST = "GET_FILTER_SIZE_REQUEST"
export const GET_FILTER_SIZE_SUCCESS = "GET_FILTER_SIZE_SUCCESS"
export const GET_FILTER_SIZE_ERROR = "GET_FILTER_SIZE_ERROR"

export const AUTOSUGGEST_REQUEST = "AUTOSUGGEST_REQUEST"
export const AUTOSUGGEST_SUCCESS = "AUTOSUGGEST_SUCCESS"
export const AUTOSUGGEST_ERROR = "AUTOSUGGEST_ERROR"

export const SQL_EDITOR_EXECUTE_REQUEST = "SQL_EDITOR_EXECUTE_REQUEST"
export const SQL_EDITOR_EXECUTE_SUCCESS = "SQL_EDITOR_EXECUTE_SUCCESS"
export const SQL_EDITOR_EXECUTE_ERROR = "SQL_EDITOR_EXECUTE_ERROR"
export const SQL_EDITOR_LOAD_QUERY_HISTORY_REQUEST =
  "SQL_EDITOR_LOAD_QUERY_HISTORY_REQUEST"
export const SQL_EDITOR_LOAD_QUERY_HISTORY_SUCCESS =
  "SQL_EDITOR_LOAD_QUERY_HISTORY_SUCCESS"
export const SQL_EDITOR_LOAD_QUERY_HISTORY_ERROR =
  "SQL_EDITOR_LOAD_QUERY_HISTORY_ERROR"
export const SQL_EDITOR_STORE_INPUT = "SQL_EDITOR_STORE_INPUT"
export const SQL_EDITOR_STORE_CURSOR_POSITION =
  "SQL_EDITOR_STORE_CURSOR_POSITION"
export const SQL_EDITOR_PRIVILEGE_ERROR = "SQL_EDITOR_PRIVILEGE_ERROR"
export const SQL_EDITOR_PRIVILEGE_ERROR_CONFIRM =
  "SQL_EDITOR_PRIVILEGE_ERROR_CONFIRM"

export const TRACK_LOAD_DASHBOARD_ERROR_STATE =
  "TRACK_LOAD_DASHBOARD_ERROR_STATE"
export const TRACK_INITIAL_RENDER_ERROR_STATE =
  "TRACK_INITIAL_RENDER_ERROR_STATE"

export const CONFIRM_LOAD_DASHBOARD_ERROR = "CONFIRM_LOAD_DASHBOARD_ERROR"

export const OPEN_MAILTO = "OPEN_MAILTO"

export const GET_HARDWARE_INFO_REQUEST = "GET_HARDWARE_INFO_REQUEST"
export const GET_HARDWARE_INFO_SUCCESS = "GET_HARDWARE_INFO_SUCCESS"
export const TRACK_INITIALIZE_DASHBOARD = "TRACK_INITIALIZE_DASHBOARD"
export const TRACK_S3_IMPORT = "TRACK_S3_IMPORT"
export const TRACK_SOURCE_IMPORT = "TRACK_SOURCE_IMPORT"

// Table Functions

export const LOAD_TABLE_FUNCTIONS_REQUEST = "LOAD_TABLE_FUNCTIONS_REQUEST"
export const LOAD_TABLE_FUNCTIONS_SUCCESS = "LOAD_TABLE_FUNCTIONS_SUCCESS"

// Control Panel
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_ERROR = "GET_USERS_ERROR"
export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST"
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS"
export const GET_ROLES_ERROR = "GET_ROLES_ERROR"

// Crossfilter
export const SET_FILTER_CROSSFILTER = "SET_FILTER_CROSSFILTER"
export const DELETE_FILTER_CROSSFILTER = "DELETE_FILTER_CROSSFILTER"
export const TOGGLE_FILTER_CROSSFILTER = "TOGGLE_FILTER_CROSSFILTER"
export const SET_FILTER_CROSSFILTER_SUCCESS = "SET_FILTER_CROSSFILTER_SUCCESS"
export const DELETE_FILTER_CROSSFILTER_SUCCESS =
  "DELETE_FILTER_CROSSFILTER_SUCCESS"
export const TOGGLE_FILTER_CROSSFILTER_SUCCESS =
  "TOGGLE_FILTER_CROSSFILTER_SUCCESS"

export const SHOW_REFRESH_MODAL = "SHOW_REFRESH_MODAL"
export const CLOSE_REFRESH_MODAL = "CLOSE_REFRESH_MODAL"

// Palette Mappings
export const APPLY_SAVED_PALETTE_MAPPING = "APPLY_SAVED_PALETTE_MAPPING"
export const CLEAR_PALETTE_MAPPING = "CLEAR_PALETTE_MAPPING"
export const CLEAR_PALETTE_MAPPING_INACTIVE_TAB =
  "CLEAR_PALETTE_MAPPING_INACTIVE_TAB"
