// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const DASHBOARD_IMPORT = "DASHBOARD_IMPORT"
export const DASHBOARD_SHARING = "DASHBOARD_SHARING"
export const DASHBOARD_BULK_SHARING = "DASHBOARD_BULK_SHARING"
export const CATEGORY_SELECTION = "CATEGORY_SELECTION"
export const CUSTOM_SQL_MANAGER = "CUSTOM_SQL_MANAGER"
export const CUSTOM_SOURCE_MANAGER = "CUSTOM_SOURCE_MANAGER"
export const COHORT_BUILDER = "COHORT_BUILDER"
export const CHART_EXPORT = "CHART_EXPORT"
export const DASHBOARD_MIGRATION = "DASHBOARD_MIGRATION"
export const PARAMETER_MANAGER = "PARAMETER_MANAGER"
export const JOIN_MANAGER = "JOIN_MANAGER"

export const CUSTOM_MODAL_TYPES_SET = new Set([
  DASHBOARD_IMPORT,
  DASHBOARD_SHARING,
  DASHBOARD_BULK_SHARING,
  CATEGORY_SELECTION,
  CUSTOM_SQL_MANAGER,
  CUSTOM_SOURCE_MANAGER,
  COHORT_BUILDER,
  CHART_EXPORT,
  DASHBOARD_MIGRATION,
  PARAMETER_MANAGER,
  JOIN_MANAGER
])

export const DANGER = "DANGER"
export const WARNING = "WARNING"
export const INFO = "INFO"
