// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const DEFAULT_PAGE_TITLE = "HEAVY Immerse"

export const LOG_DESCRIPTIONS = {
  access: "Logs requests made to or through the Heavy Immerse web server.",
  all: "Logs application output for the Heavy Immerse web server.",
  error:
    "Logs non-fatal HeavyDB error messages, as well as errors related to data ingestion.",
  heading: "View log files as plain text in your web browser.",
  info:
    "This is the best source of information for HeavyDB troubleshooting, and the first place you should check for HeavyDB issues.",
  warning: "Logs HeavyDB nonfatal warning messages."
}

export const SYSTEM_DASHBOARD_DESCRIPTIONS = {
  heading: "Interactive dashboards for exploring HeavyDB system metadata.",
  systemResources:
    "Interactive dashboard for exploring utilization of system resources.",
  requestLogs: "Interactive dashboard for request logs and monitoring.",
  rolesPermissions:
    "Interactive dashboard for roles and permissions available to users."
}

export const IQ_LOG_DESCRIPTIONS = {
  access: "Logs requests made to or through HeavyIQ.",
  all: "Logs application output for HeavyIQ.",
  console: "Logs console output for HeavyIQ.",
  build: "Logs build output for HeavyIQ.",
  guidance: "Logs application output for HeavyIQ Guidance activity."
}

export const QUERY_GENERATOR_COMPLEXITY_TEXT = {
  "1":
    "Basic SQL queries generated by a Large Language Model tend to be generated with a higher accuracy rate than more complex queries. Level 1 queries are the most basic SQL queries that retrieve data from a single table without any complex conditions or joins.",
  "2":
    "These queries include simple filtering criteria like WHERE clauses with one or two conditions.",
  "3":
    "These queries involve grouping and aggregating data using functions such as COUNT, SUM, AVG, MIN, and MAX.",
  "4":
    "These queries involve nesting one query inside another. Subqueries can be used in many ways, such as filtering, joining, or performing calculations on the results of the inner query.",
  "5":
    "These queries involve joining multiple tables together and may include multiple levels of subqueries and complex conditions. These queries require a deeper understanding of SQL syntax and data modeling."
}

export const THEMING_DESCRIPTIONS = {
  heading: "Customize the global color theme and styles for Immerse."
}

export const COLOR_PALETTE_DESCRIPTIONS = {
  heading: "Customize your global color palettes that can be applied to charts."
}
