// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

require("./core.scss")
require("./themes/dark.scss")
require("./themes/high-contrast.scss")
require("import-shims/heavyai-charting-styles")
require("./third-party-ui/mapbox-gl-draw-override.css")
require("./third-party-ui/react-grid.scss")
require("./third-party-ui/react-slider.scss")
require("./third-party-ui/react-toggle.scss")
require("./third-party-ui/react-selectize.css")
require("./third-party-ui/dropzone.min.css")
require("./third-party-ui/filepicker.css")
require("codemirror/lib/codemirror.css")
require("codemirror/addon/hint/show-hint.css")
require("./third-party-ui/react-autosuggest.scss")

/* official material css */
require("material-components-web/dist/material-components-web.css")
require("@material/button/dist/mdc.button.css")
require("@material/dialog/dist/mdc.dialog.css")
require("@material/icon-button/dist/mdc.icon-button.css")
require("@material/list/dist/mdc.list.css")
require("@material/menu/dist/mdc.menu.css")
require("@material/menu-surface/dist/mdc.menu-surface.css")
require("@material/switch/dist/mdc.switch.css")
require("@material/form-field/dist/mdc.form-field.css")
require("@material/textfield/dist/mdc.textfield.css")
require("@material/notched-outline/dist/mdc.notched-outline.css")
require("@material/line-ripple/dist/mdc.line-ripple.css")
require("@material/snackbar/dist/mdc.snackbar.css")
require("@material/checkbox/dist/mdc.checkbox.css")
require("@material/radio/dist/mdc.radio.css")

/* rmwc css */
require("@rmwc/icon/icon.css")
require("@rmwc/data-table/data-table.css")
require("@rmwc/circular-progress/circular-progress.css")
require("@rmwc/tooltip/tooltip.css")
/* custom overrides */
require("./third-party-ui/material-override.scss")

require("../components/accordion/styles.scss")
require("../components/login/styles.scss")
require("../components/dashboard/styles.scss")
require("../components/dashboards/styles.scss")
require("../components/dashboard-row-item/styles.scss")
require("../components/navigation-bar/styles.scss")
require("../components/search-input/styles.scss")
require("../components/segmented-control/styles.scss")
require("../components/count-widget/styles.scss")
require("../components/chart-editor/styles.scss")
require("../components/chart-type-button/chart-type-button.scss")
require("../components/chart-container/styles.scss")
require("../components/chart-settings-sort-by-dropdown/styles.scss")
require("../components/chart-settings-basemap-dropdown/styles.scss")
require("../components/custom-selector/styles.scss")
require("../components/custom-slider/styles.scss")
require("../components/dimension-bin-settings/styles.scss")
require("../components/dimension-time-bin-settings/styles.scss")
require("../components/hover-selector/styles.scss")
require("../components/mark-shape-selector/styles.scss")
require("../components/search-term-highlight/styles.scss")
require("../components/selector-container/styles.scss")
require("../components/share-link/styles.scss")
require("../components/table/styles.scss")
require("../components/table-picker/styles.scss")
require("../components/table-importer/styles.scss")
require("../components/table-preview/styles.scss")
require("../components/app-overlay/styles.scss")
require("../components/autocomplete/styles.scss")
require("../components/chart-settings-geojson-dropdown/styles.scss")
require("../components/dashboard-top-panel/styles.scss")
require("../components/multi-count/styles.scss")
require("../components/icon-data-source/styles.scss")
require("quill-next/dist/quill.snow.css")
require("../charts/combo/line-chart2/styles.scss")
require("../vega/styles/vega-styles.scss")
require("../vega/styles/raster-styles.scss")
require("import-shims/heavyai-d3-combo-chart-styles")
require("../components/layer-picker/styles.scss")
require("../components/layer-selector/styles.scss")
require("../components/custom-checkbox/styles.scss")
require("../components/modals/styles.scss")
require("../components/modals/dashboard-import-modal/styles.scss")
require("../components/modals/dashboard-share-modal/styles.scss")
require("../components/measure-yaxis-toggle/styles.scss")
require("../components/bar-line-toggle/styles.scss")
require("../charts/bar-chart/styles.scss")
require("../components/logo/styles.scss")
require("../components/chart-settings/styles.scss")
require("../components/logged-out/styles.scss")
require("../components/post-filter/operator-selector.scss")
require("../components/chart-legend/styles.scss")
require("../components/modals/category-selection-modal/styles.scss")
require("../containers/application-container.scss")
require("../charts/table/styles.scss")
