// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { rasterLayer } from "@heavyai/charting"

export const pointMapChart = {
  getLayerAt: (i) => pointMapChart.layers[i],
  dimensions: [
    {
      inactive: false,
      name: null,
      isBinned: false,
      isBinnable: false,
      isRequired: false,
      isError: false
    }
  ],
  filters: [],
  loading: false,
  active: true,
  version: 1,
  type: "pointmap",
  zebraStriping: false,
  dataSource: "ships_ais",
  hasError: false,
  layers: [
    {
      // Jam in the rasterLayer getTransforms instead of creating an actual rasterLayer
      getTransforms: rasterLayer("points").getTransforms,
      measures: [
        {
          isRequired: false,
          isError: false,
          inactive: false,
          name: "x",
          dataSource: "ships_ais",
          type: "FLOAT",
          precision: 0,
          is_array: false,
          is_dict: false,
          name_is_ambiguous: false,
          label: "Longitude",
          value: "Longitude",
          custom: false,
          axisLabel: null,
          loading: false,
          aggType: "Avg",
          minMax: [-90, -84.0000228881836],
          initMinMax: [-90, -84.0000228881836],
          hideOther: true
        },
        {
          inactive: false,
          name: "y",
          isRequired: false,
          isError: false,
          dataSource: "ships_ais",
          type: "FLOAT",
          precision: 0,
          is_array: false,
          is_dict: false,
          name_is_ambiguous: false,
          label: "Latitude",
          value: "Latitude",
          custom: false,
          axisLabel: null,
          loading: false,
          aggType: "Avg",
          minMax: [-28.761932373046875, 48.27567672729492],
          initMinMax: [-28.761932373046875, 48.27567672729492],
          hideOther: true
        },
        {
          inactive: false,
          name: "size",
          isRequired: false,
          isError: false,
          dataSource: "ships_ais",
          type: "SMALLINT",
          precision: 0,
          is_array: false,
          is_dict: false,
          name_is_ambiguous: false,
          label: "VesselLength",
          value: "VesselLength",
          custom: false,
          axisLabel: null,
          loading: false,
          aggType: "Avg",
          minMax: [0, 341],
          initMinMax: [0, 341],
          hideOther: true
        },
        {
          inactive: false,
          name: "color",
          isRequired: false,
          isError: false,
          dataSource: "ships_ais",
          type: "STR",
          precision: 0,
          is_array: false,
          is_dict: true,
          name_is_ambiguous: false,
          label: "Destination",
          value: "Destination",
          custom: false,
          axisLabel: null,
          loading: false,
          aggType: "# Unique",
          categories: ["VENICE", "NEW ORLEANS"],
          initMinMax: ["VENICE", "NEW ORLEANS"],
          hideOther: false,
          colorType: "ordinal"
        },
        {
          inactive: false,
          name: "orientation",
          isRequired: false,
          isError: false,
          dataSource: "ships_ais",
          type: "SMALLINT",
          precision: 0,
          is_array: false,
          is_dict: false,
          name_is_ambiguous: false,
          label: "Heading",
          value: "Heading",
          custom: false,
          axisLabel: null,
          loading: false,
          aggType: "Avg",
          minMax: [0, 511],
          initMinMax: [0, 511],
          hideOther: true
        }
      ],
      dimensions: [
        {
          inactive: false,
          name: null,
          isBinned: false,
          isBinnable: false,
          isRequired: false,
          isError: false
        }
      ],
      color: {
        customDomain: ["VENICE", "NEW ORLEANS", "GREEN BAY WI"],
        customKey: "key0",
        customPalette: {
          red: ["#ea5545"]
        },
        customRange: ["#ea5545", "#bdcf32"],
        isCustom: true,
        key: "custom",
        type: "custom",
        val: ["#ea5545", "#bdcf32"],
        column: "Destination",
        defaultOtherDomain: "Default",
        defaultOtherRange: "#27aeef",
        hideOther: false,
        initialDomain: ["VENICE", "NEW ORLEANS"],
        domainIsDirty: true
      },
      markShape: "wedge",
      dataSource: "ships_ais",
      type: "pointmap",
      densityAccumulatorEnabled: true,
      autoSize: false,
      sizeRange: [13, 25],
      cap: 10000000,
      geoJoin: {},
      legendOpen: false,
      popupEnabled: true,
      rasterShowOther: true,
      active: true,
      rasterLayerId: "rasterLayerId:-NFQpnoS4Zv3bkP5dBtm"
    }
  ],
  sizeRange: [13, 25],
  height: 388,
  width: 522,
  mapZoomCenter: {
    zoom: 8.838139507627917,
    center: {
      lng: -87.68886323981138,
      lat: 44.72617574535701
    },
    bounds: {
      lonMin: -88.08984807600314,
      lonMax: -87.28787840362,
      latMin: 44.51403015759237,
      latMax: 44.93754615074556
    }
  },
  legendLocked: false,
  measures: [
    {
      isRequired: false,
      isError: false,
      inactive: false,
      name: "x",
      dataSource: "ships_ais",
      type: "FLOAT",
      precision: 0,
      is_array: false,
      is_dict: false,
      name_is_ambiguous: false,
      label: "Longitude",
      value: "Longitude",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [-90, -84.0000228881836],
      initMinMax: [-90, -84.0000228881836],
      hideOther: true
    },
    {
      inactive: false,
      name: "y",
      isRequired: false,
      isError: false,
      dataSource: "ships_ais",
      type: "FLOAT",
      precision: 0,
      is_array: false,
      is_dict: false,
      name_is_ambiguous: false,
      label: "Latitude",
      value: "Latitude",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [-28.761932373046875, 48.27567672729492],
      initMinMax: [-28.761932373046875, 48.27567672729492],
      hideOther: true
    },
    {
      inactive: false,
      name: "size",
      isRequired: false,
      isError: false,
      dataSource: "ships_ais",
      type: "SMALLINT",
      precision: 0,
      is_array: false,
      is_dict: false,
      name_is_ambiguous: false,
      label: "VesselLength",
      value: "VesselLength",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [0, 341],
      initMinMax: [0, 341],
      hideOther: true
    },
    {
      inactive: false,
      name: "color",
      isRequired: false,
      isError: false,
      dataSource: "ships_ais",
      type: "STR",
      precision: 0,
      is_array: false,
      is_dict: true,
      name_is_ambiguous: false,
      label: "Destination",
      value: "Destination",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "# Unique",
      categories: ["VENICE", "NEW ORLEANS"],
      initMinMax: ["VENICE", "NEW ORLEANS"],
      hideOther: false,
      colorType: "ordinal"
    },
    {
      inactive: false,
      name: "orientation",
      isRequired: false,
      isError: false,
      table: "ships_ais",
      dataSource: "ships_ais",
      type: "SMALLINT",
      precision: 0,
      is_array: false,
      is_dict: false,
      name_is_ambiguous: false,
      label: "Heading",
      value: "Heading",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [0, 511],
      initMinMax: [0, 511],
      hideOther: true
    }
  ],
  markShape: "wedge",
  legendOpen: false,
  basemap: {
    label: "Current Immerse Theme",
    value: "current"
  },
  dcFlag: 951738036512685
}

export const destinationFilter = {
  appliesTo: "GLOBAL",
  name: "-NFQUbKdxDM5s1QeJ6Cs",
  enabled: true,
  simpleModeEnabled: false,
  sharedCustom: false,
  globalCustom: false,
  dataSources: ["ships_ais"],
  filter: {
    filterType: "SIMPLE",
    dataExpression: "Destination",
    dataSource: "ships_ais",
    table: "ships_ais",
    dataType: "STR",
    dataTypeIsArray: false,
    operator: "=",
    value: "GREEN BAY WI"
  }
}

export const boundingBoxFilter = {
  chartId: "2",
  appliesTo: "CROSSFILTER",
  name: "-NEMP-S8kwa4lyIhHn4K",
  enabled: true,
  dataSources: ["ships_ais"],
  filter: {
    filterType: "BOUNDING_BOX",
    dataSource: "ships_ais",
    table: "ships_ais",
    lonExpression: "Longitude",
    lonDataType: "FLOAT",
    latExpression: "Latitude",
    latDataType: "FLOAT",
    isGeoJoin: false,
    lonMin: -94.08246756,
    lonMax: -77.719252451,
    latMin: 39.117446433,
    latMax: 47.913364836,
    layerId: 0
  },
  chartFilters: [],
  chartRangeFilter: [],
  mapZoomCenter: {
    zoom: 4.4873747555232235,
    center: {
      lng: -85.9008600053337,
      lat: 43.67627779644056
    },
    bounds: {
      lonMin: -94.0824675595457,
      lonMax: -77.71925245112011,
      latMin: 39.1174464328266,
      latMax: 47.91336483608677
    }
  },
  isRangeFilter: false,
  isOldFilter: true,
  userGenerated: false
}

export const backendScatterChart = {
  getLayerAt: () => backendScatterChart,
  getTransforms: rasterLayer("points").getTransforms,
  autoSize: false,
  areFiltersInverse: false,
  cap: 2000000,
  renderArea: false,
  color: {
    customDomain: [
      "Tug",
      "Cargo",
      "0",
      "Other",
      "Passenger",
      "Tanker",
      "Dredger",
      "Wing In Grnd",
      "SAR",
      "Reserved",
      "Pilot Vessel",
      "Fishing",
      "9",
      "Cargo - Hazard A (Major)",
      "Sailing Vessel",
      "Cargo - Hazard B",
      "Tanker - Hazard B",
      "Dive Vessel",
      "unknown",
      "Tanker - Hazard A (Major)",
      "Pleasure Craft",
      "Tanker - Hazard D (Recognizable)",
      "SAR Aircraft",
      "Tanker - Hazard C (Minor)",
      "Local Vessel",
      "Port Tender",
      "Cargo - Hazard D (Recognizable)",
      "255",
      "7",
      "Cargo - Hazard C (Minor)",
      "Law Enforce",
      "Special Craft",
      "High-Speed Craft",
      "Anti-Pollution"
    ],
    customKey: "key0",
    palette: {
      type: "ordinal",
      key: "Set2",
      val: [
        "#FF2727",
        "#FF6F32",
        "#FFAF14",
        "#EBE35A",
        "#EBE35A",
        "#BCCF34",
        "#5CBFAF",
        "#3b5460",
        "#937BD9",
        "#CA51E0",
        "#FF00A8",
        "#C10E66",
        "#733700",
        "#216423",
        "#0B5489"
      ]
    },
    customRange: [
      "#5CBFAF",
      "#BCCF34",
      "#216423",
      "#EBE35A",
      "#3b5460",
      "#FFAF14",
      "#216423",
      "#FF00A8",
      "#937BD9",
      "#937BD9",
      "#937BD9",
      "#BCCF34",
      "#FF2727",
      "#733700",
      "#FFAF14",
      "#733700",
      "#5CBFAF",
      "#CA51E0",
      "#0B5489",
      "#733700",
      "#733700",
      "#C10E66",
      "#937BD9",
      "#FF2727",
      "#216423",
      "#FFAF14",
      "#5CBFAF",
      "#5CBFAF",
      "#FFAF14",
      "#FF6F32",
      "#3b5460",
      "#C10E66",
      "#937BD9",
      "#FFAF14"
    ],
    isCustom: false,
    key: "Set2",
    type: "custom",
    val: [
      "#FF2727",
      "#FF6F32",
      "#FFAF14",
      "#EBE35A",
      "#EBE35A",
      "#BCCF34",
      "#5CBFAF",
      "#3b5460",
      "#937BD9",
      "#CA51E0",
      "#FF00A8",
      "#C10E66",
      "#733700",
      "#216423",
      "#0B5489"
    ],
    column: "VesselType",
    defaultOtherDomain: "Default",
    defaultOtherRange: "#888888",
    hideOther: true,
    initialDomain: [
      "Tug",
      "Cargo",
      "0",
      "Other",
      "Passenger",
      "Tanker",
      "Dredger",
      "Wing In Grnd",
      "SAR",
      "Reserved",
      "Pilot Vessel",
      "Fishing",
      "9",
      "Cargo - Hazard A (Major)",
      "Sailing Vessel",
      "Cargo - Hazard B",
      "Tanker - Hazard B",
      "Dive Vessel",
      "unknown",
      "Tanker - Hazard A (Major)",
      "Pleasure Craft",
      "Tanker - Hazard D (Recognizable)",
      "SAR Aircraft",
      "Tanker - Hazard C (Minor)",
      "Local Vessel",
      "Port Tender",
      "Cargo - Hazard D (Recognizable)",
      "255",
      "7",
      "Cargo - Hazard C (Minor)",
      "Law Enforce",
      "Special Craft",
      "High-Speed Craft",
      "Anti-Pollution"
    ],
    lastPaletteMappingId: null
  },
  colorDomain: null,
  colorRamps: [],
  fullColorHashing: true,
  dataSelections: [
    {
      layerId: "-OIWQ2jWoevidxTIyCR5",
      table: null,
      dimensions: {
        xAxis: [],
        color: null
      },
      measures: {
        size: [],
        color: null
      }
    }
  ],
  selectedLayerId: "-OIWQ2jWoevidxTIyCR5",
  vegaSortColumn: {
    col: {
      name: "measure0"
    },
    index: 0,
    order: "desc"
  },
  presentation: {
    orientation: "column",
    gridEnabled: true,
    barValuesEnabled: true,
    baseDimensionAxis: {
      groupingMode: "grouped",
      lineAreaEnabled: false
    },
    sizeMeasurePrimaryAxis: {
      cumulativeDistributionEnabled: false,
      percentageDistributionEnabled: false,
      format: "custom-basic"
    },
    sizeMeasureSecondaryAxis: {
      cumulativeDistributionEnabled: false,
      percentageDistributionEnabled: false,
      format: "custom-basic"
    }
  },
  timeLagSettings: null,
  binSettings: null,
  numberOfGroups: 500,
  scales: {
    colorMeasure: {
      palette: {
        type: "quantitative",
        name: "mapDScale"
      },
      domain: null,
      paletteReversed: false
    }
  },
  layersLegendPinned: false,
  collapsedLegendLayers: {},
  dcFlag: 5723822424244315,
  densityAccumulatorEnabled: true,
  dimensions: [
    {
      inactive: false,
      name: null,
      isBinned: false,
      isBinnable: false,
      isRequired: false,
      isError: false
    }
  ],
  elasticX: true,
  elasticY: true,
  filters: [],
  geoJson: null,
  loading: false,
  rangeChartEnabled: false,
  rangeFilter: [],
  savedColors: {},
  sortColumn: null,
  renderTableBorders: "none",
  ticks: 3,
  title: "",
  showOther: false,
  rasterShowOther: false,
  showNullDimensions: false,
  markTypes: [],
  multiSources: {},
  legendCollapsed: false,
  showAbsoluteValues: true,
  showPercentValues: false,
  showPercentValuesInPopup: true,
  showAllOthers: true,
  linkedZoomEnabled: false,
  quickFiltersExpanded: true,
  popupEnabled: true,
  hoverSelectedColumns: [
    {
      inactive: false,
      name: "size",
      isRequired: false,
      isError: false,
      table: "ships_ais",
      type: "SMALLINT",
      precision: 0,
      is_array: false,
      is_dict: false,
      is_join: false,
      name_is_ambiguous: false,
      label: "Cargo",
      value: "Cargo",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [0, 255],
      initMinMax: [0, 255],
      hideOther: true,
      format: "custom-imperial"
    },
    {
      inactive: false,
      name: "color",
      isRequired: false,
      isError: false,
      table: "ships_ais",
      type: "STR",
      precision: 0,
      is_array: false,
      is_dict: true,
      is_join: false,
      name_is_ambiguous: false,
      label: "VesselType",
      value: "VesselType",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "# Unique",
      categories: [
        "Tug",
        "Cargo",
        "0",
        "Other",
        "Passenger",
        "Tanker",
        "Dredger",
        "Wing In Grnd",
        "SAR",
        "Reserved",
        "Pilot Vessel",
        "Fishing",
        "9",
        "Cargo - Hazard A (Major)",
        "Sailing Vessel",
        "Cargo - Hazard B",
        "Tanker - Hazard B",
        "Dive Vessel",
        "unknown",
        "Tanker - Hazard A (Major)",
        "Pleasure Craft",
        "Tanker - Hazard D (Recognizable)",
        "SAR Aircraft",
        "Tanker - Hazard C (Minor)",
        "Local Vessel",
        "Port Tender",
        "Cargo - Hazard D (Recognizable)",
        "255",
        "7",
        "Cargo - Hazard C (Minor)",
        "Law Enforce",
        "Special Craft",
        "High-Speed Craft",
        "Anti-Pollution"
      ],
      initMinMax: [
        "Tug",
        "Cargo",
        "0",
        "Other",
        "Passenger",
        "Tanker",
        "Dredger",
        "Wing In Grnd",
        "SAR",
        "Reserved",
        "Pilot Vessel",
        "Fishing",
        "9",
        "Cargo - Hazard A (Major)",
        "Sailing Vessel",
        "Cargo - Hazard B",
        "Tanker - Hazard B",
        "Dive Vessel",
        "unknown",
        "Tanker - Hazard A (Major)",
        "Pleasure Craft",
        "Tanker - Hazard D (Recognizable)",
        "SAR Aircraft",
        "Tanker - Hazard C (Minor)",
        "Local Vessel",
        "Port Tender",
        "Cargo - Hazard D (Recognizable)",
        "255",
        "7",
        "Cargo - Hazard C (Minor)",
        "Law Enforce",
        "Special Craft",
        "High-Speed Craft",
        "Anti-Pollution"
      ],
      hideOther: true,
      colorType: "ordinal",
      format: ""
    }
  ],
  active: true,
  version: 1,
  type: "backendScatter",
  zebraStriping: false,
  showNullMeasures: true,
  hasError: false,
  postFilters: [
    {
      name: "postFilter",
      required: true,
      operator: null,
      min: "",
      max: "",
      type: {
        int2: true,
        int4: true,
        int8: true,
        SMALLINT: true,
        TINYINT: true,
        INT: true,
        BIGINT: true,
        FLOAT: true,
        DOUBLE: true,
        DECIMAL: true,
        CUSTOM: true
      },
      inactive: false,
      isRequired: true
    }
  ],
  dataSource: "ships_ais",
  sizeRange: [3, 10],
  height: 518,
  width: 994,
  measures: [
    {
      isRequired: false,
      isError: false,
      inactive: false,
      name: "x",
      table: "ships_ais",
      type: "SMALLINT",
      precision: 0,
      is_array: false,
      is_dict: false,
      is_join: false,
      name_is_ambiguous: false,
      label: "VesselWidth",
      value: "VesselWidth",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [0, 100],
      initMinMax: [0, 100],
      hideOther: true
    },
    {
      inactive: false,
      name: "y",
      isRequired: false,
      isError: false,
      table: "ships_ais",
      type: "SMALLINT",
      precision: 0,
      is_array: false,
      is_dict: false,
      is_join: false,
      name_is_ambiguous: false,
      label: "VesselLength",
      value: "VesselLength",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [0, 341],
      initMinMax: [0, 341],
      hideOther: true
    },
    {
      inactive: false,
      name: "size",
      isRequired: false,
      isError: false,
      table: "ships_ais",
      type: "SMALLINT",
      precision: 0,
      is_array: false,
      is_dict: false,
      is_join: false,
      name_is_ambiguous: false,
      label: "Cargo",
      value: "Cargo",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "Avg",
      minMax: [0, 255],
      initMinMax: [0, 255],
      hideOther: true
    },
    {
      inactive: false,
      name: "color",
      isRequired: false,
      isError: false,
      table: "ships_ais",
      type: "STR",
      precision: 0,
      is_array: false,
      is_dict: true,
      is_join: false,
      name_is_ambiguous: false,
      label: "VesselType",
      value: "VesselType",
      custom: false,
      axisLabel: null,
      loading: false,
      aggType: "# Unique",
      categories: [
        "Tug",
        "Cargo",
        "0",
        "Other",
        "Passenger",
        "Tanker",
        "Dredger",
        "Wing In Grnd",
        "SAR",
        "Reserved",
        "Pilot Vessel",
        "Fishing",
        "9",
        "Cargo - Hazard A (Major)",
        "Sailing Vessel",
        "Cargo - Hazard B",
        "Tanker - Hazard B",
        "Dive Vessel",
        "unknown",
        "Tanker - Hazard A (Major)",
        "Pleasure Craft",
        "Tanker - Hazard D (Recognizable)",
        "SAR Aircraft",
        "Tanker - Hazard C (Minor)",
        "Local Vessel",
        "Port Tender",
        "Cargo - Hazard D (Recognizable)",
        "255",
        "7",
        "Cargo - Hazard C (Minor)",
        "Law Enforce",
        "Special Craft",
        "High-Speed Craft",
        "Anti-Pollution"
      ],
      initMinMax: [
        "Tug",
        "Cargo",
        "0",
        "Other",
        "Passenger",
        "Tanker",
        "Dredger",
        "Wing In Grnd",
        "SAR",
        "Reserved",
        "Pilot Vessel",
        "Fishing",
        "9",
        "Cargo - Hazard A (Major)",
        "Sailing Vessel",
        "Cargo - Hazard B",
        "Tanker - Hazard B",
        "Dive Vessel",
        "unknown",
        "Tanker - Hazard A (Major)",
        "Pleasure Craft",
        "Tanker - Hazard D (Recognizable)",
        "SAR Aircraft",
        "Tanker - Hazard C (Minor)",
        "Local Vessel",
        "Port Tender",
        "Cargo - Hazard D (Recognizable)",
        "255",
        "7",
        "Cargo - Hazard C (Minor)",
        "Law Enforce",
        "Special Craft",
        "High-Speed Craft",
        "Anti-Pollution"
      ],
      hideOther: true,
      colorType: "ordinal"
    },
    {
      inactive: false,
      name: "orientation",
      isRequired: false,
      isError: false
    }
  ],
  legendLocked: false
}
