// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const ADD_PALETTE_MAPPING = "ADD_PALETTE_MAPPING"
export const UPDATE_PALETTE_MAPPING = "UPDATE_PALETTE_MAPPING"
export const SET_LAST_PALETTE_MAPPING_ID = "SET_LAST_PALETTE_MAPPING_ID"
export const CLEAR_LAST_PALETTE_MAPPING_ID = "CLEAR_LAST_PALETTE_MAPPING_ID"
export const DELETE_PALETTE_MAPPING = "DELETE_PALETTE_MAPPING"
export const SET_PALETTE_MAPPING_NAME = "SET_PALETTE_MAPPING_NAME"
