// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const LOAD_DASHBOARD_SHARED_SETTINGS_REQUEST =
  "LOAD_DASHBOARD_SHARED_SETTINGS_REQUEST"
export const LOAD_DASHBOARD_SHARED_SETTINGS_SUCCESS =
  "LOAD_DASHBOARD_SHARED_SETTINGS_SUCCESS"
export const LOAD_DASHBOARD_SHARED_SETTINGS_ERROR =
  "LOAD_DASHBOARD_SHARED_SETTINGS_ERROR"
export const CLEAR_IMPORT_DASHBOARD_ID = "CLEAR_IMPORT_DASHBOARD_ID"
