// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const SET_CHART_BIN = "VEGA/SET_CHART_BIN"
export const CLEAR_CHART_BIN = "VEGA/CLEAR_CHART_BIN"

export const SET_BINNING_MANUAL_MIN = "VEGA/SET_BINNING_MANUAL_MIN"
export const SET_BINNING_MANUAL_MAX = "VEGA/SET_BINNING_MANUAL_MAX"
export const SET_BINNING_MANUAL_MIN_MAX = "VEGA/SET_BINNING_MANUAL_MIN_MAX"
export const CLEAR_BINNING_MANUAL_MIN = "VEGA/CLEAR_BINNING_MANUAL_MIN"
export const CLEAR_BINNING_MANUAL_MAX = "VEGA/CLEAR_BINNING_MANUAL_MAX"
export const SET_BINNING_NUMBER_OF_BINS = "VEGA/SET_BINNING_NUMBER_OF_BINS"
export const SET_BINNING_TIME_UNIT = "VEGA/SET_BINNING_TIME_UNIT"
export const SET_EXTRACT_TIME_UNIT = "VEGA/SET_EXTRACT_TIME_UNIT"

export const SET_BASE_DIMENSION_FORMAT = "VEGA/SET_BASE_DIMENSION_FORMAT"
