// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const ADD_DATA_SELECTION = "VEGA/ADD_DATA_SELECTION"
export const REMOVE_DATA_SELECTION = "VEGA/REMOVE_DATA_SELECTION"
export const SET_SELECTED_DATA_SELECTION = "VEGA/SET_SELECTED_DATA_SELECTION"
export const SET_TABLE = "VEGA/SET_TABLE"
export const SET_DIMENSION = "VEGA/SET_DIMENSION"
export const SET_MEASURE = "VEGA/SET_MEASURE"
export const CLEAR_TABLE = "VEGA/CLEAR_TABLE"
export const CLEAR_DIMENSION = "VEGA/CLEAR_DIMENSION"
export const CLEAR_CUSTOM_DIMENSIONS_BY_VALUE =
  "VEGA/CLEAR_CUSTOM_DIMENSIONS_BY_VALUE"
export const CLEAR_MEASURE = "VEGA/CLEAR_MEASURE"
export const CLEAR_CUSTOM_MEASURES_BY_VALUE =
  "VEGA/CLEAR_CUSTOM_MEASURES_BY_VALUE"

export const UPDATE_BASE_DIMENSION_SORT_COLUMN =
  "VEGA/UPDATE_BASE_DIMENSION_SORT_COLUMN"
export const UPDATE_BASE_DIMENSION_SORT_ORDER =
  "VEGA/UPDATE_BASE_DIMENSION_SORT_ORDER"
export const SET_BASE_DIMENSION_SORT_OPTIONS =
  "VEGA/SET_BASE_DIMENSION_SORT_OPTIONS"

export const SET_NUMBER_OF_GROUPS = "VEGA/SET_NUMBER_OF_GROUPS"
export const SET_NULL_DIMENSIONS_ENABLED = "VEGA/SET_NULL_DIMENSIONS_ENABLED"
export const SET_CONNECT_NULLS_ACROSS_GAPS =
  "VEGA/SET_CONNECT_NULLS_ACROSS_GAPS"
export const SET_RANGE_CHART_ENABLED = "VEGA/SET_RANGE_CHART_ENABLED"
export const SET_LEGEND_ENABLED = "VEGA/SET_LEGEND_ENABLED"
export const SET_GRID_ENABLED = "VEGA/SET_GRID_ENABLED"
export const SET_BAR_VALUES_ENABLED = "VEGA/SET_BAR_VALUES_ENABLED"
export const SET_BOX_PLOT_CENTER_LINE_TYPE =
  "VEGA/SET_BOX_PLOT_CENTER_LINE_TYPE"
export const SET_VIOLIN_DISTRIBUTION_PRECISION =
  "VEGA/SET_VIOLIN_DISTRIBUTION_PRECISION"
export const SET_OUTLIERS_ENABLED = "VEGA/SET_OUTLIERS_ENABLED"
