// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const CLEAR_ALL_CHART_FILTERS = "OMNIFILTERS/CLEAR_ALL_CHART_FILTERS"
export const CLEAR_ALL_FILTERS = "OMNIFILTERS/CLEAR_ALL"
export const CLEAR_BY_NAME = "OMNIFILTERS/CLEAR_BY_NAME"
export const CLEAR_CHART_FILTERS = "OMNIFILTERS/CLEAR_CHARTS"
export const DUPLICATE_OMNIFILTER = "OMNIFILTERS/DUPLICATE_FILTER"
export const SET_CHART_FILTER = "OMNIFILTERS/SET_CHART"
export const SET_CHART_COHORT = "OMNIFILTERS/SET_CHART_COHORT"
export const SET_CROSSFILTER = "OMNIFILTERS/SET_CROSSFILTER"
export const SET_DASHBOARD_COHORT = "OMNIFILTERS/SET_DASHBOARD_COHORT"
export const SET_DASHBOARD_FILTER = "OMNIFILTERS/SET_DASHBOARD"
export const TOGGLE_BY_NAME = "OMNIFILTERS/TOGGLE_BY_NAME"
export const TOGGLE_SIMPLE_MODE_BY_NAME =
  "OMNIFILTERS/TOGGLE_SIMPLE_MODE_BY_NAME"
export const TOGGLE_CHART_FILTERS = "OMNIFILTERS/TOGGLE_CHARTS"
export const TOGGLE_CROSSFILTERS = "OMNIFILTERS/TOGGLE_CROSSFILTERS"
export const TOGGLE_DASHBOARD_FILTERS = "OMNIFILTERS/TOGGLE_DASHBOARD_FILTERS"
export const TOGGLE_QUICK_FILTER_VISIBILITY =
  "OMNIFILTERS/TOGGLE_QUICK_FILTER_VISIBILITY"
export const UPDATE_FILTER_BY_NAME = "OMNIFILTERS/UPDATE_FILTER_BY_NAME"
export const SET_QUICK_FILTER_OPTION = "OMNIFILTERS/SET_QUICK_FILTER_OPTION"
export const CANCEL_CHART_FILTER_CHANGES =
  "OMNIFILTERS/CANCEL_CHART_FILTER_CHANGES"
export const UPDATE_FILTER_LAYER_ID_BY_NAME = "UPDATE_FILTER_LAYER_ID_BY_NAME"
