// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const SET_MEASURE_MARK_TYPE = "VEGA/SET_MEASURE_MARK_TYPE"
export const SET_MEASURE_LINE_STYLE = "VEGA/SET_MEASURE_LINE_STYLE"
export const SET_MEASURE_AXIS = "VEGA/SET_MEASURE_AXIS"

// Actions below unused for now

export const TOGGLE_MEASURE_HIDE_LINE = "VEGA/TOGGLE_MEASURE_HIDE_LINE"
export const SET_MEASURE_LINE_THICKNESS = "VEGA/SET_MEASURE_LINE_THICKNESS"
export const SET_MEASURE_LINE_SHADOW = "VEGA/SET_MEASURE_LINE_SHADOW"
export const SET_MEASURE_MARK_COLOR = "VEGA/SET_MEASURE_MARK_COLOR"
