// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const SET_ORIENTATION = "VEGA/SET_ORIENTATION"

export const SET_GROUPING_MODE = "VEGA/SET_GROUPING_MODE"
export const TOGGLE_LINE_AREA_ENABLED = "VEGA/TOGGLE_LINE_AREA_ENABLED"

export const SET_SCALE_TYPE = "VEGA/SET_SCALE_TYPE"
export const CLEAR_SCALE_TYPE = "VEGA/CLEAR_SCALE_TYPE"

export const SET_BASE_DIMENSION_TITLE = "VEGA/SET_BASE_DIMENSION_TITLE"
export const SET_PRIMARY_MEASURE_TITLE = "VEGA/SET_PRIMARY_MEASURE_TITLE"
export const SET_SECONDARY_MEASURE_TITLE = "VEGA/SET_SECONDARY_MEASURE_TITLE"

export const SET_PRIMARY_MEASURE_FORMAT = "VEGA/SET_PRIMARY_MEASURE_FORMAT"
export const CLEAR_PRIMARY_MEASURE_FORMAT = "VEGA/CLEAR_PRIMARY_MEASURE_FORMAT"
export const SET_SECONDARY_MEASURE_FORMAT = "VEGA/SET_SECONDARY_MEASURE_FORMAT"
export const CLEAR_SECONDARY_MEASURE_FORMAT =
  "VEGA/CLEAR_SECONDARY_MEASURE_FORMAT"

export const SET_PRIMARY_CUMULATIVE_DISTRIBUTION_ENABLED =
  "VEGA/SET_PRIMARY_CUMULATIVE_DISTRIBUTION_ENABLED"
export const SET_PRIMARY_PERCENTAGE_DISTRIBUTION_ENABLED =
  "VEGA/SET_PRIMARY_PERCENTAGE_DISTRIBUTION_ENABLED"
export const SET_SECONDARY_CUMULATIVE_DISTRIBUTION_ENABLED =
  "VEGA/SET_SECONDARY_CUMULATIVE_DISTRIBUTION_ENABLED"
export const SET_SECONDARY_PERCENTAGE_DISTRIBUTION_ENABLED =
  "VEGA/SET_SECONDARY_PERCENTAGE_DISTRIBUTION_ENABLED"
export const SET_MANUAL_PRIMARY_MEASURE_DOMAIN_MIN =
  "VEGA/SET_MANUAL_PRIMARY_MEASURE_DOMAIN_MIN"
export const CLEAR_MANUAL_PRIMARY_MEASURE_DOMAIN_MIN =
  "VEGA/CLEAR_MANUAL_PRIMARY_MEASURE_DOMAIN_MIN"
export const SET_MANUAL_PRIMARY_MEASURE_DOMAIN_MAX =
  "VEGA/SET_MANUAL_PRIMARY_MEASURE_DOMAIN_MAX"
export const CLEAR_MANUAL_PRIMARY_MEASURE_DOMAIN_MAX =
  "VEGA/CLEAR_MANUAL_PRIMARY_MEASURE_DOMAIN_MAX"
export const SET_MANUAL_SECONDARY_MEASURE_DOMAIN_MIN =
  "VEGA/SET_MANUAL_SECONDARY_MEASURE_DOMAIN_MIN"
export const CLEAR_MANUAL_SECONDARY_MEASURE_DOMAIN_MIN =
  "VEGA/CLEAR_MANUAL_SECONDARY_MEASURE_DOMAIN_MIN"
export const SET_MANUAL_SECONDARY_MEASURE_DOMAIN_MAX =
  "VEGA/SET_MANUAL_SECONDARY_MEASURE_DOMAIN_MAX"
export const CLEAR_MANUAL_SECONDARY_MEASURE_DOMAIN_MAX =
  "VEGA/CLEAR_MANUAL_SECONDARY_MEASURE_DOMAIN_MAX"
