// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const SET_COLOR_MEASURE_COLOR_SCHEME =
  "VEGA/SET_COLOR_MEASURE_COLOR_SCHEME"
export const SET_COLOR_DOMAIN = "VEGA/SET_COLOR_DOMAIN"
export const CLEAR_COLOR_DOMAIN = "VEGA/CLEAR_COLOR_DOMAIN"
export const TOGGLE_REVERSE_COLOR_MEASURE_COLOR_PALETTE =
  "VEGA/TOGGLE_REVERSE_COLOR_MEASURE_COLOR_PALETTE"

export const SET_COLOR_MEASURE_CATEGORICAL_PALETTE =
  "VEGA/SET_COLOR_MEASURE_CATEGORICAL_PALETTE"
export const SET_COLOR_DIMENSION_CATEGORICAL_PALETTE =
  "VEGA/SET_COLOR_DIMENSION_CATEGORICAL_PALETTE"
