// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const SET_CHART_TIME_LAG = "VEGA/SET_CHART_TIME_LAG"
export const CLEAR_CHART_TIME_LAG = "VEGA/CLEAR_CHART_TIME_LAG"

export const SET_TIME_LAG_INTERVAL = "VEGA/SET_TIME_LAG_INTERVAL"
export const SET_TIME_LAG_BINNED_TIME_UNIT =
  "VEGA/SET_TIME_LAG_BINNED_TIME_UNIT"
export const LINK_BASE_MEASURE_TIME_LAG = "VEGA/LINK_BASE_MEASURE_TIME_LAG"
export const UNLINK_BASE_MEASURE_TIME_LAG = "VEGA/UNLINK_BASE_MEASURE_TIME_LAG"
export const SET_TIME_LAG_MEASURE_MODE = "VEGA/SET_TIME_LAG_MEASURE_MODE"
