// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const TOPN_SET_OPTIONS = "TOPN/SET_OPTIONS"
export const TOPN_RESET_OPTIONS = "TOPN/INITIALIZE_OPTIONS"
export const TOPN_UPDATE_N = "TOPN/UPDATE_N"
export const TOPN_SET_MEASURE = "TOPN/SET_MEASURE"
export const TOPN_SET_MEASURE_AGGREGATE = "TOPN/SET_MEASURE_AGGREGATE"
export const TOPN_SET_SORT_ORDER = "TOPN/SET_SORT_ORDER"
export const TOPN_LOCK = "TOPN/LOCK"
export const TOPN_UNLOCK = "TOPN/UNLOCK"
export const TOPN_SET_POSITION = "TOPN/SET_POSITION"
export const TOPN_SET_COLOR = "TOPN/SET_COLOR"
export const TOPN_TOGGLE = "TOPN/TOGGLE"
export const TOPN_TOGGLE_ALL_OTHERS = "TOPN/TOGGLE_ALL_OTHERS"
export const TOPN_MANUAL_SELECTION = "TOPN/MANUAL_SELECTION"
export const TOPN_SHOW_ALL_OTHERS_IN_LEGEND =
  "TOPN/TOPN_SHOW_ALL_OTHERS_IN_LEGEND"
export const TOPN_ALLOW_NULL_KEYS = "TOPN/TOPN_ALLOW_NULL_KEYS"
export const TOPN_SET_FROM_PALETTE_MAPPING = "TOPN_SET_FROM_PALETTE_MAPPING"
