// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/* eslint-disable no-underscore-dangle */
import * as DashboardHelpers from "./dashboard-helpers"
import * as featureFlagsModule from "components/control-panel/featureflags"

const cols = 30
const layout = [
  { y: 0, x: 0, h: 10, w: 10, i: "1" },
  { y: 0, x: 10, h: 10, w: 10, i: "2" },
  { y: 0, x: 20, h: 10, w: 10, i: "3" },
  { y: 10, x: 0, h: 10, w: 10, i: "4" },
  { y: 10, x: 10, h: 10, w: 10, i: "5" },
  { y: 10, x: 20, h: 10, w: 10, i: "6" }
]

describe("dashboard helpers", () => {
  describe("#_bottom", () => {
    it("should calculate the bottom coordinate of the widget", () => {
      const widget = layout[0]
      const bottom = DashboardHelpers._bottom(widget)
      expect(bottom).toEqual(10)
    })
  })

  describe("#_right", () => {
    it("should calculate the right coordinate of the widget", () => {
      const widget = layout[0]
      const right = DashboardHelpers._right(widget)
      expect(right).toEqual(10)
    })
  })

  describe("#_calculateW", () => {
    it("should calculate the width (in grid units) of a new chart", () => {
      const w = DashboardHelpers._calculateW(30, 3)
      expect(w).toEqual(10)
    })
  })

  describe("#_calculateGridDimensions", () => {
    it("should return an array containing the dimensions of the grid", () => {
      const numRows = DashboardHelpers._calculateGridDimensions(layout, cols)
      expect(numRows).toEqual([30, 30])
    })
  })

  describe("#_generateEmptyGrid", () => {
    it("should create an empty matrix of zeros", () => {
      const grid = DashboardHelpers._generateEmptyGrid([4, 5])
      expect(grid).toEqual([
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
      ])
    })
  })

  describe("#_populateGrid", () => {
    it("should convert a layout of grid items to a binary matrix representation", () => {
      const dimensions = DashboardHelpers._calculateGridDimensions(layout, cols)
      const emptyGrid = DashboardHelpers._generateEmptyGrid(dimensions)
      const populated = DashboardHelpers._populateGrid(layout, emptyGrid)
      expect(populated).toEqual([
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ])
    })
  })

  describe("#calculateGridStates", () => {
    const _innerHeight = 895
    const _innerWidth = 960
    const _cols = 30
    const _offset = 48
    const _numVisibleRows = 2
    const _rowHeight = DashboardHelpers.calculateGridStates(
      _innerHeight,
      _innerWidth,
      _cols,
      _offset,
      _numVisibleRows
    ).rowHeight
    it("should return the height in pixels for each row", () =>
      expect(_rowHeight).toEqual(42)) // 12 with ui/minimize_chart_size
    it("should return a whole number", () => expect(_rowHeight % 1).toEqual(0))
    it("should never return below 32", () =>
      expect(
        DashboardHelpers.calculateGridStates(
          300,
          _innerWidth,
          _cols,
          _offset,
          _numVisibleRows
        ).rowHeight
      ).toEqual(32)) // 12 with ui/minimize_chart_size
  })

  describe("#findInsertionSpot", () => {
    const _innerHeight = 895
    const _innerWidth = 960
    const _offset = 48
    const _numVisibleRows = 2
    const _margin = 25
    const _chartType = "number"
    const {
      rowHeight: _rowHeight,
      colWidth: _colWidth
    } = DashboardHelpers.calculateGridStates(
      _innerHeight,
      _innerWidth,
      _offset,
      _numVisibleRows,
      _margin
    )
    const _layout = []

    beforeEach(() => {
      jest
        .spyOn(featureFlagsModule, "getFeatureFlag")
        .mockImplementation((flag) => {
          const { getFeatureFlag } = jest.requireActual(
            "components/control-panel/featureflags"
          )
          return flag ===
            featureFlagsModule.available_feature_flags.MINIMIZE_CHART_SIZE
            ? false
            : getFeatureFlag(flag)
        })
    })

    afterEach(() => {
      jest.clearAllMocks()
    })
    it("It should insert a chart at [x:0, y:0] on the first chart", () => {
      const gridItem = DashboardHelpers.findInsertionSpot(
        _layout,
        cols,
        _rowHeight,
        _colWidth,
        "0",
        _chartType
      )
      _layout.push(gridItem)
      expect(_layout[0]).toEqual({
        y: 0,
        x: 0,
        h: 10,
        w: 10,
        i: "0",
        minH: 4, // 1 with ui/minimize_chart_size
        minW: 6 // 1 with ui/minimize_chart_size
      })
    })
    it("It should insert a chart to the right previously placed chart", () => {
      const gridItem = DashboardHelpers.findInsertionSpot(
        _layout,
        cols,
        _rowHeight,
        _colWidth,
        "1",
        _chartType
      )
      _layout.push(gridItem)
      expect(_layout[1]).toEqual({
        y: 0,
        x: 10,
        h: 10,
        w: 10,
        i: "1",
        minH: 4, // 1 with ui/minimize_chart_size
        minW: 6 // 1 with ui/minimize_chart_size
      })
    })
    it("It should insert a chart to the right previously placed chart", () => {
      const gridItem = DashboardHelpers.findInsertionSpot(
        _layout,
        cols,
        _rowHeight,
        _colWidth,
        "2",
        _chartType
      )
      _layout.push(gridItem)
      expect(_layout[2]).toEqual({
        y: 0,
        x: 20,
        h: 10,
        w: 10,
        i: "2",
        minH: 4, // 1 with ui/minimize_chart_size
        minW: 6 // 1 with ui/minimize_chart_size
      })
    })
    it("It should insert on the next row because first row is full", () => {
      const gridItem = DashboardHelpers.findInsertionSpot(
        _layout,
        cols,
        _rowHeight,
        _colWidth,
        "3",
        _chartType
      )
      _layout.push(gridItem)
      expect(_layout[3]).toEqual({
        y: 10,
        x: 0,
        h: 10,
        w: 10,
        i: "3",
        minH: 4, // 1 with ui/minimize_chart_size
        minW: 6 // 1 with ui/minimize_chart_size
      })
    })
  })
})
