// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import React, { useState, useRef, useEffect } from "react"
import cx from "classnames"
import { Tooltip } from "@rmwc/tooltip"

import { Icon } from "@rmwc/icon"
import { process as processParameters } from "utils/ImmerseSQLPlusPlus/parser"
import ParameterSelectorInput from "components/parameter-selector-input"

import "./styles.scss"
import { PopoverOrientation } from "components/parameter-selector-input/constants"

const ChartTitle = ({
  chartType,
  id,
  isEditMode,
  restrictViewing,
  parametersInAutoTitle,
  parameterValues,
  title,
  updateChartTitle
}) => {
  const [inputValue, setInputValue] = useState(title)
  const [isFocused, setIsFocused] = useState(false)
  const [processedTitle, setProcessedTitle] = useState(title)
  const [parametersInTitle, setParametersInTitle] = useState(
    parametersInAutoTitle || {}
  )
  const [showTooltip, setShowTooltip] = useState(false)

  const inputRef = useRef()

  useEffect(() => {
    setInputValue(title)
  }, [title])

  useEffect(() => {
    setParametersInTitle(parametersInAutoTitle || {})
  }, [parametersInAutoTitle])

  useEffect(() => {
    setProcessedTitle(
      processParameters(title, {
        chartId: id,
        token: "chartTitle",
        onProcessComplete: ({ processedParameterValues }) => {
          setParametersInTitle(processedParameterValues)
        }
      })
    )
  }, [id, parameterValues, title])

  useEffect(() => {
    if (isFocused && inputRef.current) {
      // It might make sense to only select all if the title has
      // never been edited, i.e. it's the default auto-generated title
      inputRef.current.select()
    }
  }, [isFocused])

  const handleBlur = (e) => {
    setIsFocused(false)
    setShowTooltip(false)
    setInputValue(e.target.value)

    if (e.target.value !== title) {
      updateChartTitle(e.target.value)
    }
  }

  const handleClick = () => {
    if (isEditMode) {
      setIsFocused(true)
    }
  }

  const updateInput = (e) => {
    setInputValue(e.target.value)
  }

  const getPlaceHolderText = () => {
    const callToAction = ["table", "text"].includes(chartType)
      ? "Enter Chart Title"
      : "Leave Blank For Autogenerated Title"

    return isFocused ? callToAction : processedTitle.length ? "" : "Add Title"
  }

  const tooltipParams =
    (parametersInAutoTitle && Object.keys(parametersInAutoTitle).length
      ? parametersInAutoTitle
      : parametersInTitle) || {}

  return (
    <div
      className={cx("chart-title", {
        "draggable-container-handle": !isEditMode,
        "default-cursor": restrictViewing
      })}
      data-testid="chart-title"
      data-ui-config-id="chart-title"
      onClick={handleClick}
    >
      {isEditMode ? (
        <div
          className={cx("chart-title-edit input-with-placeholder", {
            "is-focused": isFocused
          })}
          id={`chart-${id}-title`}
        >
          <Tooltip
            content={`${Object.keys(tooltipParams)
              .map(
                (parameterName) =>
                  `$\{${parameterName}}=${tooltipParams[parameterName]}`
              )
              .join(" ")}`}
            open={Boolean(Object.keys(tooltipParams).length) && showTooltip}
          >
            <ParameterSelectorInput
              onSelectParameter={(valueWithParameter) => {
                setInputValue(valueWithParameter)
                updateChartTitle(valueWithParameter)
              }}
              inputProps={{
                ref: inputRef,
                value: inputValue,
                className: "chart-title-textarea",
                "data-testid": "chart-title-textarea",
                id: `chart-${id}-title-input`,
                onBlur: handleBlur,
                onChange: updateInput,
                onMouseOver: () => setShowTooltip(true),
                onMouseOut: () => setShowTooltip(false)
              }}
              portalProps={{
                popoverOrientation: PopoverOrientation.BOTTOM
              }}
            />
          </Tooltip>

          <div
            className={cx("placeholder", {
              hasValue: inputValue.length
            })}
          >
            <span className="placeholder-text">
              {!(processedTitle.length || isFocused) && (
                <Icon className="chart-edit-icon" icon="edit" />
              )}
              <span>{getPlaceHolderText()}</span>
            </span>
          </div>
          <span
            title={inputValue}
            className="chart-title-processed"
            data-testid="chart-title-processed"
            onMouseOver={() => setShowTooltip(true)}
            onMouseOut={() => setShowTooltip(false)}
          >
            {processedTitle && <Icon className="chart-edit-icon" icon="edit" />}
            <span data-testid="chart-title-processed-text">
              {processedTitle}
            </span>
          </span>
        </div>
      ) : (
        <div
          id={`chart-${id}-title`}
          className="chart-title-no-edit"
          data-testid="chart-title-no-edit"
          title={title}
        >
          {processedTitle}
        </div>
      )}
    </div>
  )
}

export default React.memo(ChartTitle)
